- src/styles/index.scss
- src/styles/libraries/_libraries.scss
- src/styles/libraries/reset.scss
The `gitignore` file excludes the root `lib` folder, so this PR updates the name of the lib folder inside of the old mastersass structure to `libraries` instead.
> Updating libraries folder name to avoid confusion with root lib folder

- README.md
The tool was already implemented, adding documentation on how to deploy to github pages.
No
Updates readme
https://github.com/yankaindustries/mc-components/issues/3
> Updating documentation on how to deploy storybook to github pages

- src/styles/release-candidate/components/_radio-input.scss
Radio Input label was not centered
None
> Fix Radio Input text alignment

- package.json
Temporal disable prettier-eslint and eslint --fix, we should enable it again once we tackle this issue #36 
`prettier-eslint` is uglifying the code
No
#36 and #37
> Temporal disable prettier-eslint and lint --fix

- package.json
- src/styles/libraries/_libraries.scss
Remove unnecessary dependency (slick-theme.css). The carousel has its own styling, the theme stylesheet is no needed.
> Remove unnecessary dependency

- package.json
Versioning was done manually prior to this commit, so I've
- Unpublished 0.2.1 from npm
- Deleted 0.2.1 tag on github
- Manually reverted the package json back to 0.2.0 so it's able to be versioned with the script (it's currently on 0.2.2 which might cause issues with versioning next time)
> Undoing manual versioning

- src/styles/components/forms/_input.scss
Bug was found where variable names had changed, reversing the order of padding on inputs.  This changes the variables to reflect the correct values.
Low
Changes padding from : `1.6rem` on top and `1.3rem` on sides
To: `1.3rem` on top and `1.6rem` on sides
N/A
> Flip order for input variables

- src/styles/components/buttons/_button--types.scss
- src/styles/components/buttons/_button.scss
When imported into the main masterclass repo, the c-button had the color of the button text chaned to red because of a previously defined color change on hover for anchor tags.  Instead of risking changing in masterclass repo, I'm specifying color on hover in this repo because it's lower risk (same color on default / hover).
Could unintentionally affect text color on hover state if it isn't expecting to be white when using c-buttons (unlikely)
No visual changes, fixes a bug in masterclass main repo
N/A
> Fix c button text color in hover state

- package.json
- src/styles/components/buttons/_button--types.scss
- src/styles/components/buttons/_button.scss
There are a number of different legacy button types now in the main masterclass repo. We have `mc-btn`, `mc-button`, and now `c-button`, all of which have different variants that are slightly different.
This PR is the first step towards finally cleaning that up.  This pr adds a temporary class that mirrors `c-button` called `mc-c-btn`.  This is a unique enough name to do a find and replace after cleanup is complete.  My plan is to:
- Migrate all existing `mc-btn` and `mc-button` classes to those supported by `c-button` by using the new temporary `mc-c-btn` class. 
- Once **all** buttons are consolidated in the masterclass repo, I'll find and replace all instances of `mc-c-btn` to `mc-btn` and update the component class names as well.
- From this point on, `mc-btn` will be the only button …
> Tech debt: button cleanup

- src/components/TextArea/index.js
- src/components/Tile/__snapshots__/index.stories.storyshot
- src/components/TileVideo/__snapshots__/index.stories.storyshot
- src/components/TileVideo/index.js
- src/utils/PropsTable.js
PropsTable wasn't considering non-primatives.  Now it _sorta_ handles them (does not support `shape` yet).  There is also a fix with TileVideo passing all props to the `<video>` element, causing a warning.
Low
n/a
n/a
> Fixing issue with PropsTable not reading more complex prop types

- src/components/ClickOutside/index.js
Return event to the click outside function. Useful if you want to stop the propagation of the event.
None
Component affected: ClickOutside
> ClickOutside component: Return event to the click outside function

- package.json
Update name of compiled css file and path to file in package.json
Medium (in case anyone is using the compiled css name, but unlikely since I checked the main MC repo already for imports, and the shorthand import wasn't working because the path was wrong)
No visual change
N/a
> Update package.json with correct path to styles

- .storybook/styles.scss
- src/components/AnimationHandler/__snapshots__/index.stories.storyshot
- src/components/Tile/__snapshots__/index.stories.storyshot
- src/components/TileCaption/__snapshots__/index.stories.storyshot
- src/components/TileCaption/index.js
- src/components/TileCaption/index.stories.js
- src/styles/components/_tile.scss
Allows users to choose the text positioning easily with a prop.  Options will be, but not limited to:
- left bottom
- center bottom
- left below
- center below
```
<Tile>
<TileCaption title="Someone" position="center bottom" />
...
</Tile>
```
None
Adds the ability to change the position of the titles in TileCaption to handle more design use cases.  By default will be the same as it was (left bottom positioning).
#13 #14
> Adding position prop to TileCaption

- src/components/FoundationType/__snapshots__/index.stories.storyshot
- src/components/FoundationType/index.stories.js
- src/styles/typography/base.scss
The typography styles target h1 - h6 and the paragraph tag, which leads to style conflicts when `mc-components` is imported into another codebase.  We should only use classes to specify heading and body styles.
Low - I don't believe anywhere is relying on the styles in mc-components for type yet.
https://github.com/yankaindustries/mc-components/issues/133
> Updating typography to not target direct elements

- src/components/AnimationHandler/__snapshots__/index.stories.storyshot
- src/components/Button/__snapshots__/index.stories.storyshot
- src/components/Button/index.stories.js
- src/components/HoverHandler/__snapshots__/index.stories.storyshot
- src/components/Tile/__snapshots__/index.stories.storyshot
- src/components/Tile/index.stories.js
- src/components/TileCaption/__snapshots__/index.stories.storyshot
- src/components/TileCaption/index.stories.js
- src/components/TileCheck/__snapshots__/index.stories.storyshot
- src/components/TileCheck/index.stories.js
- src/components/TileImage/__snapshots__/index.stories.storyshot
- src/components/TileImage/index.stories.js
- src/components/TileOverlay/__snapshots__/index.stories.storyshot
- src/components/TileOverlay/index.stories.js
- src/components/TileVideo/__snapshots__/index.stories.storyshot
- src/components/TileVideo/index.stories.js
- src/components/ToggleHandler/__snapshots__/index.stories.storyshot
- src/components/ToggleHandler/index.stories.js
- src/utils/DocSection.js
- src/utils/PropExample.js
Noticed that the type styles broke when I made a change to the css in https://github.com/yankaindustries/mc-components/pull/134 for heading text.
Low - only affects storybook styles.
No visual changes in components, only to storybook stories!
https://github.com/yankaindustries/mc-components/issues/135
> Updating type in storybook

- src/components/Foundation/Type/index.stories.js
- src/styles/libraries/_libraries.scss
- src/styles/typography/modifiers.scss
- src/utils/CodeExample.js
Adding in a few text helpers:
```
<p class="mc-text-uppercase">This text is uppercased</p>
<p class="mc-text-lowercase">This text is lowercased</p>
<p class="mc-text-capitalize">This text is capitalized</p>
<p class="mc-text-bold">This text is a normal font weight (400)</p>
<p class="mc-text-normal">This text is a bold font weight (700)</p>
<p class="mc-text-muted">This text is muted (50% opacity)</p>
<p class="mc-text-left">Left aligned text on all viewport sizes.</p>
<p class="mc-text-center">Center aligned text on all viewport sizes.</p>
<p class="mc-text-right">Right aligned text on all viewport sizes.</p>
<p class="mc-text-sm-left">Left aligned text on viewports sized SM (small) or wider.</p>
<p class="mc-text-md-left">Left aligned text on viewports sized MD (medium) or wider.</p>
<p …
```
> Add font helper functionality like in bootstrap

- .eslintrc
- src/components/Carousel/index.js
- src/components/Foundation/Type/index.stories.js
- src/components/Modal/index.js
- src/components/ModalPortal/index.js
- src/components/RoundedBox/index.stories.js
I fixed the JS lint warnings that I was able to fix.  We went from 43 warnings to 8!
None
No visual changes, but removed the requirement in eslint for:
```
"react/boolean-prop-naming": 0,
"react/jsx-handler-names": 0
```
https://github.com/yankaindustries/mc-components/issues/145
> Clean up the easy JS lint warnings

- src/components/Button/index.js
- src/components/Button/index.stories.js
- src/styles/components/buttons/_button--types.scss
- src/styles/components/buttons/_button.scss
The default button state (without properties) didn't look quite right, so let's make the primary button style the default style.
Low - primary isn't used specifically in many places, but I've updated the component and checked in our repo for usage.  If a third party were using the primary class before, the default button would now have their desired styles.  A specific use case is in the masterclass repo here:
```
/app/views/accounts/_form.html.slim
```
Visually no change, but default button component now uses primary styles
https://github.com/yankaindustries/mc-components/issues/82
> Make primary button style the default style

- .storybook/webpack.config.js
It's starting to get complicated enough that a new dev without domain knowledge might have some issues with tracking down where styles are coming from. Add in sourcemaps for easier code groking. 
None
N/A
https://github.com/yankaindustries/mc-components/issues/155
> Add sourcemaps for storybook for easier css troubleshooting

- src/components/HeaderLoggedIn/index.stories.js
- src/components/HeaderLoggedOut/index.stories.js
- src/styles/components/_header-logged-out.scss
- src/styles/components/_header.scss
Get the logged in and logged out heights to be the same.
Medium - the header heights are finicky but we aren't using the new header anywhere yet in the masterclass repo.
Visually subtle changes - height of both logged in and logged out headers are now the same.
First step of: https://github.com/yankaindustries/mc-components/issues/157
> Sync header heights

- README.md
- src/styles/typography/_typography.scss
- src/styles/typography/fonts.scss
We're importing the font multiple times in the main repo. We'll remove it from mc-components as a direct import and let consumers know that they need to manually import the font.
Low
Visually removes font family, relies on it being imported manually now.
https://github.com/yankaindustries/mc-components/issues/163
> Remove font

- .storybook/_upside-down.scss
- src/styles/base/_variables.scss
- src/styles/typography/base.scss
Defines color variables for background, text color, and sets them on body
Adds new variables: 
```
$mc-color-background:        #090909 !default;
$mc-color-background-invert: #ebeeee !default;
$mc-color-text:              #272c33 !default;
$mc-color-text-invert:       #8ca1c1 !default;
```
And sets them by default on body - now when you import mc-components' styles into a page, you'll get the black background and white text by default.
None - checked mc repo and mc-components for variable use and does not exist.
N/A
https://github.com/yankaindustries/mc-components/issues/183
> Define color variables for body background and text colors

- src/components/VideoPlayer/index.js
- src/components/VideoPlayer/index.stories.js
- src/components/VideoPlayerEndScreen/index.js
- src/components/VideoPlayerScreen/index.js
- src/styles/components/_video-player.scss
Currently, we only support end screen overlay. This PR allows us to add a custom overlay screen.
None, end screen component should is still working with this change.
Resolves #186
> VideoPlayer: Before and Paused overlay screens

- src/foundation/type/index.stories.js
- src/styles/typography/base.scss
- src/styles/typography/modifiers.scss
Consolidate heading styles for a standardized h1-h5 and display 1-3
Low - verified there is only one place we currently use `mc-text-h2` in the main repo, will shift text slightly (letter spacing change) but is not a dealbreaker.
Minor visual changes to one location where h2 is currently being used, but that shift is ok to consolidate type styles.
https://github.com/yankaindustries/mc-components/issues/182
> Consolidate heading type styles

- src/styles/base/_variables.scss
- src/styles/typography/base.scss
Resize text elements based on viewport width.  These values will most likely change, but add in support to easily update as the design comp becomes more finalized.
Low - this will most likely visually affect our components as we tweak the font sizes with design.  We are ok with visual changes due to these updates.
- Default body font got a slight size bump
- Text default is from 0 - "small" (576px)
- Next breakpoint is from "small" (576) - "large" (992px)
- Last breakpoint (biggest text) is from "large" (992px) and up.
https://github.com/yankaindustries/mc-components/issues/178
> Adding responsive typography per design comp

- src/components/AnimationHandler/index.stories.js
- src/components/Background/index.js
- src/components/Carousel/index.stories.js
- src/components/Tile/index.stories.js
- src/components/TileCaption/index.js
- src/components/TileCaption/index.stories.js
- src/components/TileCheck/index.stories.js
- src/components/TileImage/index.js
- src/components/TileImage/index.stories.js
- src/components/TileOverlay/index.stories.js
- src/styles/components/_background.scss
- src/styles/components/_tile.scss
- src/styles/typography/modifiers.scss
A handful of improvements to Tile components:
- TileImage implements Background, which allows MC to pass it a Cloudinary image without "clouding" up the component library
- TileCaption removed `title` and `subtitle` so that users can pass their own typographic needs as `children`
- Removed inset border of Tile
None - while they introduce breaking changes, they are not currently used in MC
-
#195 #198
> Tile improvements

- src/foundation/variables/index.stories.js
The variables "story" wasn't updated when the grid variable was updated. This brings them in sync.
> Updating variables in storybook to reflect current breakpoint variables

- .storybook/_upside-down.scss
- src/components/Tile/index.stories.js
- src/components/TileCaption/index.stories.js
- src/components/TileCheck/index.stories.js
- src/components/TileImage/index.stories.js
- src/components/TileOverlay/index.stories.js
- src/components/TileVideo/index.stories.js
- src/foundation/variables/index.stories.js
- src/styles/base/_variables.scss
- src/styles/libraries/bootstrap-overrides/_grid.scss
There was a misalignment of expectations between design and development on how the grid works.  We spoke with Sean and got clarification on how design would like to have the grid implemented and these code changes reflect those discussions.
Any components using the existing grid might have edge cases while hitting breakpoints that could visually break them.  @jstnjns and I will be going through existing components to verify there are no breaking changes as well as the masterclass repo before versioning mc-components.  We would like to get this change in ASAP so any developers building new components will be using the grid now vs later.  There should be a separate PR in the next few days to adjust any existing components to work with the new grid.
Per Jesse, these items in the main …
> Updating breakpoints

- src/styles/base/_variables.scss
- src/styles/typography/base.scss
Grays were out of order and corrected in figma comp, so updating here as well.
Low, but colors may change if they were using the variables (intentionally / acceptable though)
Grays can now be used gray-100 (darkest) to gray-600 (lightest) as one would expect.  Also cleaned up "slightly different" grays used in edge cases to instead use the closest standard grays available (secondary / tertiary variables).
https://github.com/yankaindustries/mc-components/issues/210
> Updating color variables

- src/styles/components/_tile.scss
We are removing a legacy tile classnames as they are just conflicting with what's on prod, and should be cleaned out anyway.
Low - We checked tile implementations in `masterclass` to see if there were any conflicts with removing these classes, they are using the local implementation anyway so there appears to be no issue...so long as we didn't miss any.
> Legacy classnames

- src/styles/libraries/_libraries.scss
- src/styles/libraries/bootstrap-grid/_functions.scss
- src/styles/libraries/bootstrap-grid/_grid.scss
- src/styles/libraries/bootstrap-grid/_variables.scss
- src/styles/libraries/bootstrap-grid/bootstrap-grid.scss
- src/styles/libraries/bootstrap-grid/mixins/_breakpoints.scss
- src/styles/libraries/bootstrap-grid/mixins/_grid-framework.scss
- src/styles/libraries/bootstrap-grid/mixins/_grid.scss
- src/styles/libraries/bootstrap-grid/utilities/_display.scss
- src/styles/libraries/bootstrap-grid/utilities/_flex.scss
- src/styles/libraries/slick-carousel/slick.scss
This is a workaround for dependency issue with importing bootstrap and slickslider into other projects that depend on mc-components (like the rails asset pipeline).  Since we keep running into issues with pathing for styles, this brings in the actual styles for both bootstrap grid and slick slider.
- These libraries are not updated frequently
- This resolves the importing issues we're seeing on webpack / rails
- This is easy to update if we decide to update either slick slider or the grid in the future
- While not ideal (code can be duplicated), the performance hit and complexity is minimal for the big win of not having to deal with pathing issues anymore.
Low
Slick slider and bootstrap grid are no longer node dependencies, but css files imported / exported in mc-components.
N/A
> Fix for rails pipeline css consumption issues

- src/styles/libraries/_libraries.scss
- src/styles/libraries/bootstrap-overrides/_grid.scss
- Tiles on homepage were not using the correct gutter sizes
- Account edit page was broken from using the `col` name in the middle of a class name.
- The overrides were imported in the wrong order, causing the overrides to not apply to vertical gutters
Low - If any classes begin with `col`, they will inherit the bootstrap grid styles.  We will eventually use bootstrap's method of looping through each column type and breakpoint so collisions have a nil chance of happening.
Changes columns behavior
> Reduce wildcard specificity of column selector

- src/components/HoverHandler/index.js
- src/components/HoverHandler/index.stories.js
To avoid wild actions when cursor moves across a grid where tiles are listing for hover, we've added `intent` so that you can listen to hover only when the user has stopped moving the mouse.
None - This is adding functionality, not changing any.
> Adding `intent` value to HoverHandler

- src/components/AnimationHandler/index.stories.js
- src/components/Carousel/index.stories.js
- src/components/Tile/index.stories.js
- src/foundation/type/index.stories.js
- src/playground/home/index.stories.js
- src/styles/typography/modifiers.scss
The current `--light` and `--normal` text modifier styles render the same since we only import a few font weights.  Update the storybook documentation to reflect this.
None
https://github.com/yankaindustries/mc-components/issues/234
> Remove unused --light style and readd --x-light to documentation

- src/styles/components/modal/_modal-header.scss
Subheader style was not taking into consideration due to a wrong className.
Minor fix, no risks.
Now the modal will use the defined subheader style.
> Subheader style fixed

- src/foundation/grid/index.stories.js
- src/styles/libraries/bootstrap-overrides/_grid.scss
Grid padding isn't always needed, so we'd like to be able to support rolling your own padding options.  This new `.row.no-gutters-vertical` option (which is used on `.row` elements) will remove only the vertical padding between rows.
None - not even used yet, new style
https://github.com/yankaindustries/mc-components/issues/224
> Add no-gutters-vertical class

- src/styles/base/_variables.scss
- src/styles/libraries/bootstrap-overrides/_grid.scss
After building an example experiment, we realized the `64px` of padding on the container was excessive for tablets.
This PR updates the grid system to maintain the `32px` of left and right padding on the container until you hit the large breakpoint of `960px` before switching to the `64px` of padding.
Low - all grids are being updated but this should give everything more breathing room.
Old grid at `769px`:
New grid at `769px`
https://github.com/yankaindustries/mc-components/issues/233
> Updating gutter widths after experimenting with real implementation

- .storybook/_upside-down.scss
- src/foundation/variables/index.stories.js
When comparing comps to the "variables" page of the storybook app, it was hard to pick a specific color.  Since the figma comps usually specify hex values and not a variable name, it was impossible to visually identify which color you needed.  This PR adds the hex values for each color into the documentation, and should be automatically updated if we ever change the CSS variable file...automagically.
None
Adds hex values to 'variables' page in storybook documentation
https://github.com/yankaindustries/mc-components/issues/232
> Add hex values to documentation in variables section

- src/components/Modal/index.js
- src/components/Modal/index.stories.js
- src/components/ModalContent/index.js
- src/styles/components/_modal.scss
The original Modal component was a little less flexible than what this component library is expected to be, so this is a replacement.  
Medium - All modal implementations will need to be replaced.  We are not keeping around the legacy implementation to simplify adoption this time.
The new biggest change to the Modal component is that it isn't very concerned with how it looks.  The only decision that has been made is where the close button lives (outside, top right, which I think to be reasonable to expect consistency in), as well as a semi-transparent black background.  Other than that, structural styling is decided by what other components you decide to use.
There are actually two components that are necessary, `Modal` and `ModalContent`.  Below you'll see why we need `ModalContent`. …
> Building new <Modal /> component

- src/components/Footer/index.js
- src/styles/components/_footer.scss
Masterclass footer needs to be updated to support a sitemap link.
https://masterclass-dev.atlassian.net/wiki/spaces/VI/pages/47973549/Create+and+programmatically+update+HTML+and+XML+sitemap?focusedCommentId=52166987#comment-52166987
None
Adds new link to footer, renames "Help Center" to "Support" to save horizontal space, adjust css to fit one more link on desktop before breakpoint shrinks.
https://github.com/yankaindustries/mc-components/issues/247
> Adding sitemap link to footer

- src/components/VideoPlayer/index.js
Fix for safari: Prevent checking buffers if the video is not using HLS
Low
> Prevent checking buffers if the video is not using HLS

- src/foundation/type/index.stories.js
- src/styles/typography/base.scss
- src/styles/typography/modifiers.scss
The new SEO page relies heavily on typography and is the perfect test arena for mc-components typography. While working to build out the page, I adjusted the typography we have in mc-components to work with this page.  This is an ongoing learning experience and we will continue to update type styles in the future, but this is a good starting point.
No risk for mc-components, but medium risk for the masterclass repo. We are using existing type styles in a few locations in the masterclass repo (outlined below) - these areas will need to be verified as acceptable before versioning.
Type updates - font sizing, responsive type changes, new type headings
N/A
- Base font size now set to 16px and 1.5 line height
- `h1` changed from `32px` on desktop to `48px`
- `h2` changed from `24px` on desktop …
> Updating typography to work with seo page and future pages

- src/components/Forms/index.stories.js
- src/components/Textarea/index.js
- src/components/TextareaField/index.stories.js
- src/styles/components/forms/textarea/_default.scss
Textareas currently don't show errors if no label value exists.  This is incorrect, and fixed in this PR.  Also, added textarea to form overview in Storyboard.
None
#267
> Having Textarea properly display error when no label exists

- src/styles/components/forms/textarea/_default.scss
Labels are absolutely positioned, but no container on Textarea is the relative beginning.  This fixes that.
None
#268
> Fixing label for textareas not wrapped in .form-group

- src/components/Button/index.stories.js
- src/styles/components/buttons/_button--types.scss
Link Buttons did not have the same padding/spacing as regular buttons, making them display oddly when next to each other.  This fixes that.
None
#242
> Fixing Button link styles

- src/styles/base/_functions.scss
Bugfix for broken `mc-text--center` classes in 0.8.0. I didn't include `breakpoint-min()` which was causing the class to be generated as `mc-text-xs--center`
> added missing bootstrap fn for generating mc-text--center classes

- src/styles/components/forms/_structure.scss
`.form-group` bottom margin was set to the same value as the grid gutter.  on larger screens, this value is 32px, but is way too large.  so we stop the growth at medium, 16px.
None
> minimizing form group margin, 32px is way too big

- src/styles/typography/_base.scss
- src/styles/typography/_beta.scss
Beta typography needs to be scoped to beta pages only
Low, increasing specificity to beta stuffs
Prevents beta typography changes from bleeding into production stylesheets
N/A
> Scope beta stuff to beta pages

- src/styles/components/buttons/_button--types.scss
Design is not a fan of the underline style used for the "link" button type.  The style was originally pulled from the login link at the top right of the logged out homepage, but they've said it's not a style (in terms of animation) that they'd like to use, so this PR removes that animation type from button links.
None, design is approved
Removes left to right underline animation, replaces with simpler animation.
https://github.com/yankaindustries/mc-components/issues/285
> Updating underline styles for button link types

- src/styles/components/buttons/_button--types.scss
Slight revision to previous animation change to underlines on button link styles. I assumed incorrectly that some animation would be acceptable, it was not :( Updating to simply be opacity on button links moving forward
None, approved by design
Underlines simply fade in and out on hover
https://github.com/yankaindustries/mc-components/issues/285
> No transitional, just opacity

- src/components/ImageTile/index.js
- src/components/Tile/index.js
- src/styles/components/_tile.scss
Add 9x16 aspect ratio tiles to our available tiles per new design comps. This will be a reused style moving forward.
None
Adds new available aspect ratio for tile images
N/A
> Adding 9 by 16 tile ratios

- src/components/Input/index.js
Show the label when the input wasn't touched
None
Resolves #292
> Don't show the error label if the input wasn't touched

- src/components/Carousel/index.js
- src/components/Carousel/index.stories.js
- src/styles/components/_carousel.scss
- src/styles/components/_tile.scss
Slick slider has a "dots" option to add thumbnail dots to a slider. This PR adds some styles to override their default, as well as passes along the option as a boolean.
None...I don't know if this is the right way to do this, or if I should pass a bunch of options, including custom markup like the `arrows` example. Will have @jstnjns weigh in on this.
N/A
> Adding dots to carousel

- src/styles/components/buttons/_button.scss
Figma comps were showing 12% for letter spacing, which was different than our original values - I think I forgot to update the letter spacing values when the buttons were finalized.
Low
N/A
> Updating letter spacing for consistency

- src/components/Carousel/index.js
- src/components/Carousel/index.stories.js
- src/styles/components/_carousel.scss
Issue with overflowing container widths on the fadeEdges carousel. Removing until solution is found since this carousel isn't used anywhere
None
https://github.com/yankaindustries/mc-components/issues/296
> Temporarily removing fadeEdges until needed, implementation is flawed

- src/styles/base/_variables.scss
- src/styles/components/buttons/_button--types.scss
Tertiary button colors regressed when they were updated :/
None
(Lesson title was missing)
N/A
> Fixing tertiary color regression

- src/components/Tile/index.stories.js
- src/components/TileCaption/index.js
- src/components/TileCaption/index.stories.js
- src/styles/components/_tile.scss
We need more control over tile caption positioning.  This adds x and y axis control for how the caption aligns.
TileCaption previously did not have x and y values, so any place that TileCaption is currently used needs to be updated.  It looks like it's only used at the following location in the main repo right now:
`app/javascript/packs/client/features/promotions/BogoPage/BogoPage.js`
This will be a **breaking change** for anyone that is currently using `TileCaption` or the styles associated with it in their project.  This should be communicated to everyone.
N/A
> Updating positioning for tilecaption

- src/components/Tile/index.js
- src/components/Tile/index.stories.js
- src/styles/components/_tile.scss
Will noticed a new style / aspect ratio for a tile he was working on for the new instructor announcement banner experiment.  Confirmed with Sean that a new aspect ratio will be needed moving forward: 21:9.
None, doesn't affect existing components, merely adds a new option.
N/A
> Adding 21x9 tile aspect ratio

- README.md
- src/components/VideoPlayer/index.js
- hide beforescreens, pausescreens, and endscreens when you play or seek on a video. This allows you to rewatch a video from an endscreen by just clicking play, and lets you seek on a video without the dark overlay from the pausescreen being activated.
- updated the readme with more detailed instructions on how to link in your repo (for other masterclass frontend noobs like me who got a little lost trying to do it for the first time)
- Low? It affects the video player, but only if there are pausescreens, endscreens, and beforescreens (and only if they are open). I manually tested this on Playlists and on the Chapters#Watch page videos.
- Hides the pausescreen when seeking on a video:
- Hides the endscreen (and pausescreens & beforescreens) when playing a video, which allows you to rewatch …
> VideoPlayer: hide before/pause/endscreens on play & seek for video

- src/styles/base/_variables.scss
Background got changed to #090909 when a lot of the masterclass app is based on a completely black background.  This fixes that.
None
> back in black

- src/styles/base/_variables.scss
Somehow REM base font size got set back to 16 (possibly bad merge/rebase)?!  Changing back to 10.
None
> Changing REM base to 10px

- src/components/Carousel/index.js
- src/styles/components/_carousel.scss
Content in a carousel was being cut off when overflow hidden was set.  Update carousel component to support overflowing content more gracefully.
Low - existing implementation should be unaffected by this change.
- Removes "draggable" tiles
- Adds subtle opacity animation as slides come in / exit
- Adds support for hover states of tiles growing outside of bounding area of carousel
https://github.com/yankaindustries/mc-components/issues/320
> Updating carousel for overflowing hover effects

- src/styles/components/_tile.scss
There was an issue with the tileOverlays being too large or too small for the tiles because of overflows and a 1px "rounding error" from subpixel calculations in CSS.  While troubleshooting, I found that centering a background linear gradient will force calculations to match the parent containers better, and resolves (for the most part) the issue we're seeing.
There is still a rendering issue where the tile overlay is calculated incorrectly and "off by one" pixel on hover, but it won't be noticeable on 99% of the tiles.
Low
Fixes 1px miscalculation on tile overlays
https://github.com/yankaindustries/mc-components/issues/297
> Fix tile overlay background issue

- src/styles/components/_carousel.scss
Adding additional breathing room for vertically overflowed items in carousel
Low
Allows hover transitions to grow outside of container bounds
N/A
> Bugfix for Carousel overflow

- src/foundation/grid/index.stories.js
- src/styles/base/_body.scss
- src/styles/helpers/_grid.scss
- src/styles/helpers/_helpers.scss
Add helper class for breaking content out of container
Medium - adds `overflow-x: hidden;` to body, so this has the potential to cause issues with overflowing content.
https://github.com/yankaindustries/mc-components/issues/273
> Add helper class for breaking content out of container

- src/components/Carousel/index.js
- src/components/Carousel/index.stories.js
- src/styles/components/_components.scss
- src/styles/components/carousel/_base.scss
- src/styles/components/carousel/_carousel.scss
- src/styles/components/carousel/_modifiers.scss
Adds two new properties to the carousel component:
- `highlightOnActive` when set will dim all non focused slides
- `highlightOnHover` when set will dim all slides except the slide you hover over
None - new properties
https://github.com/yankaindustries/mc-components/issues/314
> Add highlightOnActive and highlightOnHover props to carousel component

- src/components/Button/index.js
- src/styles/components/buttons/_button--inverted.scss
- src/styles/components/buttons/_button--types.scss
`<Button linkMuted />` looks like a disabled `<Button link />` so we are killing it.
None, the removal of `linkMuted` instances has already been done in `masterclass`
#283
> Removing linkMuted from <Button />`

- src/styles/components/forms/input/_default.scss
- src/styles/components/forms/input/_modifiers.scss
This is a fix for input labels error states and hover styles.
Low - some changes to CSS, but intended to fix an existing bug, so hopefully an improvement :D
Based on [figma comps](https://www.figma.com/file/X4sR3879DmwTYCRG72WKquAP/Components---In-Progress?node-id=4079%3A1901) per design.
Previous error state:
New:
https://github.com/yankaindustries/mc-components/issues/281
> Adding better handling for form input states like hover and error

- package.json
We don't do anything with lint warnings, and they are just piling up.  If we want to address the warnings, we should make the rules actual errors instead.  This PR quiets the warnings.  We can address them later if we want to, but I don't see a need.
None
#145
> quiet those lint warnings, we dont need em

- src/styles/components/buttons/_button--types.scss
The original ticket was to create new variables for buttons so they were specifically set with intent.  I believe an extra layer of abstraction here isn't warranted - setting the gray colors specifically communicates to future devs updating button codes exactly what these colors are / do without having to look them up in variables.
None - old variable names are still there for now until the code freeze is over and we can safely remove the references to them in the mc repo.
No visible changes
https://github.com/yankaindustries/mc-components/issues/302
> Remove abstraction for button colors so colors are more obvious

- src/components/Background/index.stories.js
- src/components/Carousel/index.stories.js
- src/playground/home/index.stories.js
- src/playground/typography/index.stories.js
- src/styles/base/_beta.scss
- src/styles/helpers/_helpers.scss
- src/styles/helpers/_spacing-margin.scss
- src/styles/helpers/_spacing-padding.scss
- src/styles/helpers/_spacing.scss
Adds spacing helpers for margins and padding.  It seems like overkill, but after building a few features, we've discovered the majority of CSS needing to be written is for these variables (margins and padding).  These helper classes will allow users to quickly add the spaces they need with some helper classes, while keeping the look consistent with the type scale.  We shouldn't have "custom" values for margins and padding anymore once this is in.
None - updated previous "beta" examples where applicable, these are all new classes.
Adds ability to use class names like `mc-mb-5` to add a `margin-bottom` value of "5" from the type scale. 
N/A
> Spacing helpers

- src/components/Footer/index.js
Updates the copyright year on the footer. Uses Date() instead of hardcoded value so it can be automatically updated in the future. 
None
https://masterclass-dev.atlassian.net/browse/VIR-185
> Update copyright year on footer

- src/styles/components/forms/textarea/_default.scss
Textarea labels are aligned incorrectly when wrapped inside of a container with `text-align: center;` - this forces the correct left-alignment.
None
Keeps labels aligned to the left.
https://github.com/yankaindustries/mc-components/issues/336
> Fix label alignment for textareas

- src/foundation/typography/summary.stories.js
Sean requested that we add a button to preview the "hinted" style in the [storybook documentation](https://ourmasterclass.slack.com/archives/CB74RPL82/p1548284229029500). We should display it so users can see what it looks like.
None - just a storybook change
Adds button on "summary" page of typography to showcase the muted style.
N/A
> Add hinted modifier button to documentation

- src/components/Modal/index.js
- src/components/VideoPlayer/index.js
- Added `appendToBody` to Modal to disable/enable react portal appending to body
- Added fullscreen event listener to VideoPlayer to toggle `appendToBody` in chapter video NPS survey
None
No changes, all new props are optional
> modify Modal and VideoPlayer component to work with fullscreen NPS survey

- package.json
- src/foundation/spacing/index.stories.js
Add documentation for margin and padding helpers in mc-components.
None - only affects documentation
Adds new documentation page in storybook for margin and padding helper css classes.
https://github.com/yankaindustries/mc-components/issues/354
> Adding documentation for margin and padding helpers

- src/styles/index.scss
- src/styles/libraries/_libraries.scss
libraries should be included at the root level, if you don't want them then you can import the stuff you do want.
high, we'll need to change all instance that include libraries and the index separately
> Incorporating libraries into main by default

- .storybook/config.js
When loading storybook, force the "intro" summary story to load first.
None - documentation update
Now loads the summary / introduction story first instead of accordion.
N/A
> Force storybook to load the introduction story first

- src/styles/base/mixins/_step.scss
- src/styles/typography/_base.scss
All major measurements (anything using the step scale) is based in REM, and therefore `html { font-size: ____; }`.  We are forcing the value of this so that we can expect consistent sizing throughout the library.
Low - if our application is expecting to be able to set the font-size of the `html` attribute anywhere, this will override it.  However, we are globally loading mc-components, and anywhere the app might be doing this would cause rendering issues anyway.
Stuff ALWAYS renders properly
> making sure the html font size stays as we set it

- src/styles/base/_variables.scss
- src/styles/components/_video-player.scss
Our Brightcove player overrides the `button` tag styles for some reason when player is fullscreen.  This override messes with our button styles because the selector is more specific (class + element) than our button styles selector (class).  This adds a more specific selector to the button styles (class + class) in addition to the original.
None
Buttons in video screens when the video player is in fullscreen mode render properly.
> Augmenting buttons within the video player to override the overrides (`.bc-player button`)

- src/components/FormGroup/index.js
- src/components/Forms/index.stories.js
- src/styles/libraries/bootstrap-overrides/_grid.scss
Adjusting labels and support text for form groups to not be static width.
None
#380
> Improving label, error, and help text rendering when content is large

- src/components/Accordion/index.js
- src/components/Accordion/index.stories.js
Adding prop to limit or fill the number of panes to show in an Accordion.
Low - if someone is already using the Accordion, they might need to update the prop if their needs differ from standard usage.
#392
> Adding showCount to Accordion

- src/styles/body/_body.scss
Fix the overflow of the body on iOS caused by tiles overflowing the row
Low
Fixes this:
https://github.com/yankaindustries/mc-components/issues/399
> Fix overflow on body for iOS devices caused by overflowing tile rows

- src/styles/components/buttons/_button--types.scss
- src/styles/components/buttons/_button.scss
https://ourmasterclass.slack.com/archives/CB74RPL82/p1552516077019600
Design updated the padding on buttons, so this implements those new values, and ties them to the scale system (which didn't exist when buttons were first created! #progress)
Low - the padding changes slightly so we'll have some shifting of button elements on the page, but nothing should be broken.
Slightly narrower now!
This also changes our buttons from using borders to using inset box shadows instead so we no longer have to worry about buttons shifting when they change from having no borders to borders like from this bug:
https://github.com/yankaindustries/mc-components/issues/379
https://github.com/yankaindustries/mc-components/issues/400
> Updating button padding to new design specs

- src/components/FormGroup/index.js
form labels and other text is often affected by text alignment set in a parent container.  we don't want to have to reset as these will always stay the same, so a simple override at the form group level works
none
> Forcing form group text alignments

- src/styles/components/carousel/_base.scss
Change the arrow from 50% opacity when disabled to being fully hidden when disabled.  Disabled meaning there are no more slides to display in that particular direction.
None
Left arrow before:
Left arrow  after:
https://github.com/yankaindustries/mc-components/issues/410
> Updating carousel arrow implementation

- src/styles/body/_body.scss
The previous fix for the iOS scrolling issue introduced a new "double scrollbar" issue.  This PR consolidates the double overflow settings to just live on the `html` element which seems to fix the original issue on iOS and resolve the double scrollbar issue on desktop.
Low
N/A
> Fix double body scrollbar

- src/styles/components/_video-player.scss
there is a bug on video players across the site where two cc icons are showing up (one subtitles, the other captions).  this is most likely due to brightcove forcing the version of our player to a newer one (that happens to contain this bug).  their solution is to update to a new major version, but that's a big undertaking (which we have started).  this is the temporary solution, brought to you by @a-axton 
low - if for some reason a player only has the captions button, this could hide that.  not a terrible problem, and the bug appears to affect all players so i don't anticipate this actually being a problem
from
to
note that the cog icon removal isn't part of this, and is only a difference between local and prod
> temporarily fixing double subtitles/cc button

- src/foundation/scale/scale.stories.js
@fsarachu noticed an error in the documentation around how to include the step mixin.  This corrects that issure.
None, documentation change only
> Update incorrect documentation terminology

- src/styles/components/_video-player.scss
This style was too broad, and not necessary.  Removing it will make custom endscreens (which I thought were only on actual VideoPlayer components) work properly on all legacy BC players
Low
> Video Player Styles Improvement

- src/components/TileOverlay/index.js
Update TileOverlay's gradient-left values to match Design's request for the Accordion usecase
Low - only being used on new LIHP project's accordion component
Before:
After:
https://github.com/yankaindustries/mc-components/issues/424
> Update gradient-left values for Accordion's TileOverlay usecase

- src/styles/components/carousel/_modifiers.scss
Carousel had some bugs with the `highlight` properties.  Because the css selector was on all slides, it was overriding the default css for "peek" attributes.
Low
https://github.com/yankaindustries/mc-components/issues/430
> Updating css selector to fix carousel highlight bugs

- src/components/Accordion/index.stories.js
- src/components/Tile/index.stories.js
The supported aspect ratios for the `Accordion` and `Carousel` components weren't documented.
None - documentation change only
Adds listing of available aspect ratios to storybook examples for Accordion and Carousel
https://github.com/yankaindustries/mc-components/issues/432
> Adding documentation for all aspect ratios

- src/components/TileVideo/index.js
- src/components/VideoPlayer/index.js
- src/styles/components/_tile.scss
TileVideo needs to `event.stopPropagation()` so that a `Tile.onClick` (or any parent, for that matter) isn't triggered when trying to mute.
None
> mute stops event bubbling so that you can click it and still have a Tile.onClick

- src/components/Carousel/index.js
To calculate the Carousel's end we were using `children.length`.  This is actually not the correct approach, and is causing issue with some of our usages.  Replacing it with `React.Children.count(children)` (the correct approach) fixes this.
None
> using React.Children.count() instead of children.length

- src/components/VideoPlayer/index.js
safari has it's own restrictions on autoplaying videos if the video has audio.  however, safari allows videos that are muted to play, so we are updating our logic accordingly.  eventually this logic will be abstracted to autoplay feature detection, but until now this is a simple implementation
None
#107
> allowing autoplay for safari if the video is muted

- src/components/FormGroup/index.js
- src/components/Forms/constants.js
- src/components/Forms/index.stories.js
- src/components/Forms/utils.js
- src/components/Input/index.js
- src/components/InputField/index.js
- src/components/InputField/index.stories.js
- src/components/Select/index.js
- src/components/SelectField/index.js
- src/components/SelectField/index.stories.js
- src/components/Textarea/index.js
- src/components/TextareaField/index.js
- src/components/TextareaField/index.stories.js
- src/styles/components/forms/_element.scss
- src/styles/components/forms/_structure.scss
- src/styles/typography/_modifiers.scss
Adding `success` to FormGroup and other form elements (input, textarea, select).  This will allow us to override `help` with a success message in green.
None - just adding a new state
#457
> Form group/success

- src/components/Checkbox/index.js
- src/components/CheckboxField/index.stories.js
- src/components/Forms/constants.js
- src/components/Forms/index.stories.js
- src/components/Forms/utils.js
- src/components/Input/index.js
- src/components/InputField/index.js
- src/components/InputField/index.stories.js
- src/components/RadioField/index.stories.js
- src/components/Select/index.js
- src/components/SelectField/index.js
- src/components/SelectField/index.stories.js
- src/components/Textarea/index.js
- src/components/TextareaField/index.js
- src/components/TextareaField/index.stories.js
So that we don't have to modify multiple places when adding functionality to form elements, the prop types and message parser are being abstracted to const/utils files.
There's also a slight improvement (heavy on _slight_) in documentation explaining form elements relative to ReduxForm.
None - Nothing new, just a new place for the same things.
> Forms - Constants / Utils Abstraction

- src/styles/body/_body.scss
Adding default link styles to mc-components. Basically removes the default anchor underline.  This was previously in `mc-fe-styles`. Moving it here to consolidate.
Low - some cases we might intend to have underlines, but having the default switch to "none" is low risk - they can be added back in where there's a noticed difference if needed.
Links no longer have underlines by default.
N/A
> Adding default anchor link styles

- src/styles/components/_modal.scss
In Safari, `mc-modal` was not laying on top of the body content correctly, with lower level z-indexed items somehow making their way on a higher layer. #soelevatedbro 
The core issue was how opacity and animation keyframes interact.  The default behavior of animation keyframes in css is to revert to the default styles on the element after the animation is finished.  In this case, it animates from `opacity: 0;`, to `opacity: 1;`, then back to having no opacity definitions at all (neither `0` nor `1`).
Our animation keyframe mixin was animating with the `animation-fill-mode` property set to `forwards`. This means that when the animation is complete, the css leaves the end value of the animation active (`opacity: 1`;).  
Unfortunately, when setting opacity on an element, you start a new …
> Fix bug with modal not zindexing above content

- src/components/VideoPlayer/index.stories.js
- src/styles/components/_video-player.scss
Removing the background of a VideoPlayer screen.  This way the implementor has complete control over how screens are displayed.
Low - implementations need to be updated, this is easy with the recent changes to `<Background type='dim' fit='container' />`
> Removing default background for VideoPlayer screens

- src/foundation/typography/modifiers.stories.js
- src/styles/typography/_modifiers.scss
The storybook examples of link types had incorrect hover states.
None
Underline should no longer disappear on link types when hovered
N/A
> Fixing anchor styles on hover

- src/components/Button/index.js
- src/components/Button/index.stories.js
- src/styles/base/_variables.scss
- src/styles/components/_badge.scss
- src/styles/components/_icons.scss
- src/styles/components/_rounded-box.scss
- src/styles/components/_video-player.scss
- src/styles/components/buttons/_buttons.scss
- src/styles/components/forms/_checkbox.scss
- src/styles/components/forms/_element.scss
- src/styles/helpers/_corners.scss
- src/styles/helpers/_helpers.scss
Adds a "symmetrical" and "rounded" property to the button component:
The rounded property can also be added to any image or block element with `.mc-corners--circle`
None
- Updated buttons to have "symmetrical" padding when that property is set
- Added new helper class to set any block element to have a full border radius (maybe avatars in the future?)
N/A
> Adding a rounded class helper and symmetrical icon styles

- .babelrc
- package.json
- src/components/helpers.js
- src/components/index.js
- yarn.lock
Added a default export to helpers. I changed the way it was imported because it's needed to make mc-component tree shakable by webpack using `babel-plugin-transform-imports`.
The babel transform makes certain assumptions for component names.
* Assumes icons are all named properly as IconName and the actual file path is Icons/Name
* Assumes all the exported component names match the component folder name
```
transform: function(importName) {
if (importName.includes('Icon')) {
const iconImport = importName.replace('Icon','')
return `mc-components/dist/components/Icons/${iconImport}`
}
return `mc-components/dist/components/${importName}`
},
```
no changes
> changing how helpers are imported

- src/foundation/typography/modifiers.stories.js
- src/styles/typography/_modifiers.scss
Added additional line helpers for "max-height" lines.  This is useful if you want to have three lines of text truncated, but NOT have it take up the three lines of height.
None
https://github.com/yankaindustries/mc-components/issues/493
> Expanding line helper support

- src/styles/base/mixins/_step.scss
Our step mixin was including breakpoints for values that remained the same for lower values. This added extra media queries that didn't need to be there.
None
> only include media queries in step mixin if they are needed

- src/components/AnimationHandler/index.stories.js
- src/components/Background/index.stories.js
- src/components/Carousel/index.stories.js
- src/components/CarouselConnector/index.stories.js
- src/components/Dropdown/index.stories.js
- src/components/FormGroup/index.js
- src/components/HoverHandler/index.stories.js
- src/components/Icons/index.stories.js
- src/components/Modal/index.stories.js
- src/components/ResponsiveHandler/index.stories.js
- src/components/Tile/index.stories.js
- src/components/ToggleHandler/index.stories.js
- src/components/VideoPlayer/index.stories.js
- src/foundation/grid/index.stories.js
- src/foundation/scale/index.stories.js
- src/foundation/spacing/index.stories.js
- src/foundation/typography/modifiers.stories.js
- src/foundation/typography/summary.stories.js
- src/foundation/utilities/index.stories.js
- src/foundation/utilities/opacity.stories.js
- src/foundation/variables/index.stories.js
- src/playground/home/index.stories.js
- src/playground/lihp/index.stories.js
- src/styles/helpers/_helpers.scss
- src/styles/helpers/_opacity.scss
- src/styles/typography/_modifiers.scss
- src/utils/DocHeader.js
- src/utils/PropExample.js
Updates the text modifier opacity helpers to be named more generically since we're using it in many different use cases now.
This is a *breaking change* - we will need to update all the implementations in the main masterclass repo before this can be merged in.
This will need to be find / replaced in the main repo:
from `.mc-text--hinted` to `.mc-opacity--hinted`
from `.mc-text--muted` to `.mc-opacity--muted`
from `.mc-text--silenced` to `.mc-opacity--silenced`
Changes naming of `mc-text--subtle` to `mc-opacity--subtle` (and same for hinted and silenced).
https://github.com/yankaindustries/mc-components/issues/516
> Changing opacity helper naming

- src/styles/components/_tooltip.scss
While @felipegarcia92 was paying back some tech debt on custom built tooltips (because mc-components didn't have tooltips yet!), he noticed that the tooltips were not showing up when used inside of a modal.  After some troubleshooting, we discovered that the tooltips were indeed rendering, but under the modal.
Because of how tooltips are moved to the body of the page and outside of the dom flow, they were being hidden behind the higher z-indexed modal.  We have a list of z-index variables in our variables file, so I used the tooltip variable which seems to resolve the issue:
```$mc-zindex-dropdown-backdrop:  900 !default;
$mc-zindex-dropdown:          1000 !default;
$mc-zindex-sticky:            1020 !default;
$mc-zindex-fixed:             1030 !default;
$mc-zindex-modal-backdrop:    1040 …
```
> Adding proper z-indexing for tooltips

- src/components/VideoPlayer/index.js
- src/components/VideoPlayer/index.stories.js
Video screens seemed to be rendered while the video player was still initializing.  This caused the before screen to return null (as it won't render unless it is passed the video root element.  Because nothing is re-triggering a re-render, the beforescreenElement would never properly render.  Switching the root element to be stored in state causes the render to run again once it is changed.
Low, this doesn't change the implementation side of things, just the mechanism that causes the render to trigger (state change) more reliably
n/a
n/a
> Fixing screens when the render runs after the player initializes

- src/components/VideoPlayer/index.js
- src/styles/components/_tile.scss
- src/styles/components/_video-player.scss
TileVideo can be in Tiles that are not 16x9, but they show letterboxing.  This is not ideal, so I've update the VideoPlayer to support containers/players that are any aspect ratio.
Medium - Will need to test live video instances to make sure no unintended consequences occur, and double check 2x3 TileVideo instances.
> VideoPlayer - Crop video for non-16x9 player sizes.

- .github/pull_request_template.md
While versioning mc-components, I realized it'd be much easier to notice if a user adds a breaking change by specifying (instead of messaging each contributor). In the future, might be helpful to add a label instead maybe? But for now this should be good.
> Updating PR template to indicate whether prs are breaking

- src/styles/components/_video-player.scss
Fixing error with video positioning put in the wrong class: https://github.com/yankaindustries/mc-components/pull/531/files#diff-2f33716a65e49723d1d1364fc58fe514R192
Low - undoing class renaming
> fixing video player class name

- .eslintrc
- src/components/Dropdown/index.js
- src/components/Tooltip/index.js
Tooltip and Dropdown cannot rely on any implementation of their children, so we are using ReactDOM to find the nearest DOM element to use for relative spacing.
Low - not used in a lot of cases, but this is reverse compatible.
> Making TooltipToggle the most versatile

- src/components/Button/index.js
We no longer support the button type props directly on the button, they're now "`kind`s" instead.  We kept them around to make sure we wouldn't break anything in the main mc repo, but this removal means we'll need to go back through the main mc repo to make sure we don't have any regressions.
Low - we haven't supported this officially in a while
Removes the prop types on the buttons, they _must_ be specified as `kind` now.
https://github.com/yankaindustries/mc-components/issues/361
Not backwards compatible...will need to insure all `<Button>` implementations are using the correct syntax (already did a scan and only found one use case, which will be updated)
> Remove legacy button support

- src/components/Icons/index.js
- src/styles/components/_icons.scss
First step for issue #532 - need to make sure we use the `mc-icon` class before documenting it for others to use.
None, should have no perceptible changes
Syntax updating
https://github.com/yankaindustries/mc-components/issues/532
> Update icons to actually use the mc-icon class

- src/styles/components/_video-player.scss
There was an annoying issue where the control bar of the videoplayer was not lining up where your cursor was hovering. This was due to a previous bugfix for an issue where the video player wasn't occupying the full width / height of the parent container, so we had applied a `scale(1.01)` modifier with re-centering code.  Unfortunately this introduced the bug that was reported.
We've resolve the bug by adding a series of overflows / scaling to adjust correctly without affecting playhead positioning (we think).
Low - should be a patch, but always a risk of unintended consequences.
Fixes playhead weirdness on hover (doesn't line up correctly with where your cursor is)
https://github.com/yankaindustries/mc-components/issues/564
> Fixing alignment issues with video player

- src/foundation/typography/sizes.stories.js
I wanted to be able to show the rendered font size for each of the type values.  Sometimes you have a size and need to know which class you should use. This should make it easier to work with :D
None, documentation change only
The type page will now show the calculated pixel value of the type next to each item.
N/A
> Adding inline rendered font size

- src/components/Modal/index.js
fixed modal underlying body positioning so that the scroll offset doesn't get reset
None
currently if you're scrolled down on the homepage (logged out state) and click login, the homepage gets scrolled to the top:
https://masterclass-dev.atlassian.net/browse/DS-146
backwards compatible
> DS-146 modal scroll to top

- package.json
- yarn.lock
Storybook deployer was no longer compiling styles when deployed (it would only compile locally). @a-axton and I weren't able to figure out what exactly changed between versions so rolling back the deployer to the working version to get this working again.
None
N/A
N/A
N/A
> Roll back storybook deployer because it wont compile styles

- src/styles/components/_tile.scss
Noticed we had an incorrect value for the background-repeat property on `TileImage`s. Quick and easy fix!
None - previous property wasn't doing anything.
Fixed background-repeat to be correct value
N/A
> Fixing incorrect TileImage prop

- src/components/VideoPlayer/index.js
The VideoPlayer, if mounted and then unmounted before the video was ready, would continue to run (due to the video instance not being completely "disposed" of).
None
https://github.com/yankaindustries/mc-components/issues/585
> VideoPlayer - fix unmounting bug

- src/components/Carousel/index.js
- src/styles/components/carousel/_modifiers.scss
Carousel `controls` were getting cut off when combined with `variableWidth` and/or `peek` due to the styles being tested in isolation.  Styles have been updated to work together.
Additionally, the `className` being passed to the parent container in some cases (cases where there aren't enough tiles to fill the width) had potential to cause a flexbox issue.  This is now fixed by moving the passed `className` inside of the container styles.
None
> Fixing conflicts Carousel style conflicts

- src/styles/components/_dropdown.scss
just a tiny fix for the dropdown content overflow scrolling
Low
currently header and footer aren't sticky in 'actions' dropdown
this change just fixes that:
no issue currently being tracked
backwards compatible
> fixing borked dropdown content overflow

- src/components/Tile/index.js
- src/styles/components/_tile.scss
adding a prop check for onClick, which will in turn add a pointer style to the Tile component if present
Low: if merged before the mc refactor, some tiles may be missing pointer styles.  Should be no risk otherwise
will remove pointer styles from any Tiles which do not have any onClick props or are not otherwise custom-styled to have pointer
https://github.com/yankaindustries/mc-components/issues/495
May remove pointer styles from some tiles (see above).  Otherwise backwards compatible
> [DNM] adding pointer style if tile has onClick prop set

- src/styles/base/_theme-css-vars.scss
Fixing hr text modifier inverted color according to Figma's design.
> Fix hr text modifier color

- src/foundation/utilities/index.stories.js
- src/foundation/utilities/theme.stories.js
Add documentation for the change from `mc-invert` to `mc-theme-light` and `mc-theme-dark`
Just a documentation change, no risk
Adds new story under "utilities" for the themes
Part of https://github.com/yankaindustries/mc-components/issues/600
> Updating documentation for themes

- src/components/Icons/index.stories.js
- src/foundation/utilities/theme.stories.js
- src/styles/base/_theme-css-vars.scss
Add better documentation for the icon sizing class helpers
None - documentation change only
Adds documentation to icon sizing
https://github.com/yankaindustries/mc-components/issues/532
> Adding icon sizing documentation

- src/foundation/introduction/index.stories.js
https://ourmasterclass.slack.com/archives/CB74RPL82/p1572550370020300
@missx found that I incorrectly linked to the nasdaq website "npm.com" vs the actual, y'know, npmjs site.  This fixes that link :P 
None, just documentation update
Updates link to mc-components in readme
N/A
> Fix npm link in introduction

- src/components/Dropdown/index.stories.js
- src/components/DropdownItem/index.js
- src/components/helpers.js
- src/styles/helpers/_opacity.scss
`DropdownItem` automatically closes the dropdown when you click on it.  This should have been an opt-in prop, but I made it automatic.  This PR fixes that.
Additionally, `onClick` for the child of `<DropdownToggle>` was being overridden making it impossible for a controlled dropdown to be opened by it's own toggle.  `renderChildren` was extended to support firing the `onClick` of both the DropdownToggle and child.
Low - we will need to update existing implementations if autoclosing is expected
Breaking - requires update in existing implementation
> Dropdown - Fixing close functionality

- src/components/FormGroup/index.js
- src/components/Forms/index.stories.js
- src/components/TextareaField/index.js
Fixes:
• Include the input value to calculate the length
• Add an example
• Fix alignment when the text helper isn't present
None. We are not using the max length validation yet.
> BUG: maxlength text wasn't working for TextArea component

- src/components/FormGroup/index.js
- src/components/Forms/index.stories.js
- src/components/TextareaField/index.js
Reverts yankaindustries/mc-components#613
Introduced a minor regression in wrapping for text counter form input.  @bernabe9 to submit new PR following this revert.
> Revert "BUG: maxlength text wasn't working for TextArea component"

- src/components/FormGroup/index.js
- src/components/Forms/index.stories.js
- src/components/TextareaField/index.js
- src/styles/helpers/_spacing-margin.scss
The `maxlength` prop for TextArea (the character count label) was being pulled to the left alignment when there was no helper text displayed.
This PR:
- Adds margin auto helpers (`mc-ml-auto`, others)
- Fixes alignment of the maxlength text to the right of the box when there is no supporting text in the left
None
New margin helpers for "auto"! for Top, Right, Left, Bottom, X, and Y
N/A
> Fix textarea maxlength value and alignment

- src/components/VideoPlayer/index.js
As common practice, I added passing the props from wrapper component VideoPlayer onto video player tag.
Low
Just code-wise, any extra prop shouldn't bother with the video tag.
> Passing all props from VideoPlayer onto video tag

- src/components/Button/index.js
Example with `react-router`'s Link component:
```javascript
import { Link } from 'react-router'
<Button as={Link} to={path.myPathname}>Link to path</Button>
```
None
Update Button component proptypes
> Update 'as' proptype in Button to support React components

- src/components/Dropdown/index.js
- src/components/DropdownItem/index.js
Takes care of warnings for passing non-standard HTML attributes to DOM elements (specifically around Dropdown components)
None - should not change implementation, just removes warnings
> pulling props out of being passed to dropdown components

- src/components/Dropdown/index.js
- src/components/Dropdown/index.stories.js
Adds an optional prop `fixed` for Dropdown, to prevent jittery scrolling behavior. Also adds a fixed parent dropdown to the storybook dropdowns page.
Low
When you add the optional `fixed` prop on a Dropdown, the dropdown scrolls smoothly attached to its fixed parent rather than jittery because we are passing a fixed option to Popper which we use for dropdowns
https://masterclass-dev.atlassian.net/browse/RET-1147
> Dropdown with Fixed option, to prevent jittery scroll behavior

- src/components/Modal/index.js
- src/components/Modal/index.stories.js
- src/styles/components/_modal.scss
Refactoring Modal component to simplify the containers, make them a little more legible, and to clean up the body anti-scrolling and long, scrolling modals.
Low - impacts MOST modals in mc (there are some plain-old bootstrap modals still)
no intended behavioral differences, except contents are no longer cutoff
https://github.com/yankaindustries/mc-components/issues/628
backwards compatible
> Modal body scroll & overflow refactor

- src/components/TileOverlay/index.js
- src/components/TileOverlay/index.stories.js
- src/styles/components/_tile.scss
While building out a feature:
I noticed a gap in our ability to deliver the UI in question.  This PR adds a new overlay type of "solid" adding to our gradient and spotlight options.
None, new prop type
Adds new prop for `TileOverlay`
N/A
> Adding overlay type of solid for TileOverlay

- package.json
- src/components/VideoPlayer/index.js
- src/components/VideoPlayer/index.stories.js
- src/components/VideoPlayerPortalScreen/index.js
- src/components/VideoPlayerScreen/index.js
Autoplay for inline videos on mobile wasn't working.  Essentially, muting wasn't working properly, which Mobile Safari requires in order to autoplay.
Medium - Affects autoplay for all players
n/a
> VideoPlayer - Autoplay Fix

- src/styles/components/_dropdown.scss
Update dropdown height from 50vh to 75vh
Low
Height of dropdown changes from 50 > 70vh
https://github.com/yankaindustries/mc-components/issues/635
Potential issues with overflowing height off edge of screen, but acceptable to regress so "Non Breaking Change"
> Updating height of dropdown to 75vh

- .circleci/config.yml
- yarn.lock
@a-axton pointed out that Node 8.12.0 is EOL so updating our circleCI to use 10.17.0 instead to future proof us for a while.  Also updated some other packages that were safe to update.
Low
N/A
N/A
> Update node 8.12.0 > 10.17.0

- .eslintrc
- src/components/Dropdown/index.js
- src/components/DropdownContent/index.js
- src/components/DropdownContentControlled/index.js
Moved the html classname addition/removal from Dropdown to DropdownContentControlled, so that the latter would appropriately add the necessary class when shown
Low
Just moves the addition/removal of the 'mc-dropdown__html--open' class to/from the <HTML> tag when the DropdownContentControlled component is shown and closed
> Moved Html Class changes from Dropdown to DropdownContentControlled

- src/styles/components/forms/_checkbox.scss
- src/styles/components/forms/_radio.scss
As part of a code review, I noticed an override was being set for checkbox button alignment. At some point our values for the radio buttons and checkboxes changed and no longer line up with the text correctly, so this adjusts them to vertically align better again.
Comparison (animated):
None
Vertically adjusts positioning of radio button
Part of: https://github.com/yankaindustries/mc-components/issues/656
> Fix alignment for radio and checkboxes

- src/components/VideoPlayer/index.js
some minor fixes for the onPlay, onPause and onFullscreenChange event props/handlers for the MCC.VideoPlayer component.  Also snuck in the removal of the 'required' flag for the playerId prop.
Low - the fore-mentioned handlers were actually getting called twice, inadvertently.  If any of the VideoPlayer implementations were actually depending on this for whatever reason, they may break after 'fixing' this problem
Should prevent onPlay, onPause, onFullscreenChange from firing twice
N/A
should be backwards compatible, except as fore-mentioned in the risks section
> Remove on[Play|Pause|FullscreenChange] from <video> component

- src/components/VideoPlayer/index.js
Currently, when the VideoPlayer loops playback, it depends on native HTML5 video 'loop' property.  Upon the 2nd iteration of the video, it no longer fires any of the event handlers.  Instead of this approach, we're removing the native loop, and we're relying on the handleEnd method to restart/loop the playback
None
allows for proper event handling on subsequent playback iterations
N/A
> Fix VideoPlayer Looping

- src/components/VideoPlayer/index.js
BC player LOVES to send pause events... sometimes I feel like it just gets bored (j/k).  It sends pause events when the video completes, so I've added a check to omit that.
Low - only risk is if somebody is doing something frisky with the pause events.  I've performed a quick search and found no such thing
prevents this from happening at the end of a video:
N/A
N/A
> Omit the pause event if at end of video

- src/foundation/typography/modifiers.stories.js
Noticed we didn't have documentation for some of the text class helpers.
None - documentation changes only.
Added some capitalization documentation:
And some weight documentation:
N/A
> Update documentation for type styles

- src/components/VideoPlayer/index.js
there currently exists protection against backward scrubbing in the MCC.VideoPlayer component.  This is ill-placed in the MCC repo, and is MC-specific.  Therefore it should be in the MC.VideoPlayer component instead, to keep the MCC component more generic.
Low
Simply removes the protection against backward scrubbing and onTimeChange()
N/A
> [WA-131] Removed the backwards scrubbing protection around onTimeChange()

- src/components/ScrollHandler/index.js
Add `end` prop to `ScrollHandler` component. The idea is add other point where if user scrolls down that given point `scrolled` turns `false`.
If no `end` prop is passed to `ScrollHandler` the component acts as always.
Low
> Add end prop to ScrollHandler

- src/foundation/utilities/opacity.stories.js
Adding values for opacity helpers to documentation so that you don't have to inspect to get the number value.
None
https://github.com/yankaindustries/mc-components/issues/634
> Adding opacity values to documentation

- src/styles/helpers/_helpers.scss
- src/styles/helpers/_interactive.scss
A lot of custom CSS is simply setting a component to appear clickable to the user with a cursor pointer.  Instead of having to write custom CSS for this, here's a helper class.
None
None
https://github.com/yankaindustries/mc-components/issues/621
> Helper Class - `mc-clickable`

- src/components/VideoPlayer/index.js
there was an issue discovered where autoplay was throwing an exception.  This is as designed per browser autoplay policies
Google AutoPlay Policy Changes:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#new-behaviors
None
Before:
After:
N/A
> Adding catch for blocked autoplay

- src/components/Background/index.js
- src/components/Background/index.stories.js
- src/styles/components/_background.scss
The Background component used JS to decide how to place the image.  This is easily doable now with CSS, so this PR replaces that logic.
Low - tested all permutations I could think of, potential that one is missed.
No visible changes
https://github.com/yankaindustries/mc-components/issues/611
> Background - replacing JS positioning logic with CSS

- src/components/TileOverlay/index.js
- src/styles/components/_tile.scss
Sets default color for TileOverlay to be `$mc-color-gray-100` (except `spotlight` which is meant to fade the content into the background), and adds color overrides for all overlay types, not just gradients.
Low - all tiles that use default color will now switch to the dark gray overlay.  This should, however, be fine
> improving implementation of tile overlay colors

- src/components/Checkbox/index.js
- src/components/Radio/index.js
Checkbox and Radio components were double firing their `onChange` callback when clicked.  This is because clicking the label also triggers a click on the child input.  By moving the `onClick` handler to the input, we avoid double firing said handler.
None
https://github.com/yankaindustries/mc-components/issues/652
> Fix checkbox/radio double onChange

- src/styles/base/mixins/_ratios.scss
There's some old code associated to tiles / aspect ratios.  Kill it ded.
Low - looked for anywhere that was implementing `aspect-ratio` mixin to see if it relied on the old classes `.content` and `.background`.  There was a single case, and it was not.
None
https://github.com/yankaindustries/mc-components/issues/358
> killing extra garbage in aspect-ratio mixin

- src/styles/components/_video-player.scss
Videos on some devices fullscreen were cutting off necessary content (because the screens themselves are not perfectly 16x9.  This fixes that by removing the "fill" functionality when in fullscreen.
None
https://github.com/yankaindustries/mc-components/issues/598
> getting rid of video fill for fullscreen

- src/components/Tooltip/index.js
<General description>
Tool tip creates the anchor before assets render so going to call update on toggle
<What's the risk level of merging this in? | None / Low / Medium / High>
> Fix Tooltip to update anchor on toggle

- src/components/Checkbox/index.js
- src/components/Checkbox/index.stories.js
- src/components/Radio/index.js
- src/components/Radio/index.stories.js
Fixes `Checkbox` and `Radio` component's lack of onChange firing when clicked.  This was caused by a "fix" for the onChange double firing.  The issue here is that the test was done in a story that actually implements `CheckboxField` and `RadioField`, which add their own layer of handling that masked the non-click.
None - fixes bug with checkboxes.  Added unique stories for proof.
https://github.com/yankaindustries/mc-components/issues/652
> fixing radio/checkbox click events

- src/styles/components/_tile.scss
Removing scale responsible for overcompensating for off sub-pixel rendering.  That has been fixed, so we are removing the scaling.
None - minimal UI update
https://github.com/yankaindustries/mc-components/issues/297
> remove scale for tile overlay

- src/components/VideoPlayer/index.js
Play video when hasAutoplay changes.
Checked with @jstnjns on Mastercalss main repo and didn't found any hasAutoplay dynamic props that this would affect, except for `browse-trailers` page (that we will have to check) and the feature I'm working on that inspires the change.
I'm productizing `home_page_vide_player_v1` and as a design requirement I was asked to play video when users click on category set by default. Since the video for default category is placed on first component render, click on it doesn't trigger video to play since videoId doesn't change.
I try to change dynamically `hasAutoplay` prop but still wasn't able to get video to play.
Without `hasAutoplay` reacting to changes:
With `hasAutoplay` reacting to changes:
It's a more elegant solution that getting video instance from …
> Play if hasAutoplay changes

- src/components/Carousel/index.js
- src/components/Carousel/index.stories.js
- src/styles/components/carousel/_modifiers.scss
adding the ability to set the gradient color for peeking
Low - default color is still black.  Should see no observable difference in behavior without this new prop.
N/A
> New Color Prop for Carousels with Peek

- src/components/Carousel/index.js
when using the `peek` prop with carousel, it also forces `focusOnSelect` - I'm simply removing the forcing of `focusOnSelect` when using the peek prop.
None
N/A
N/A
> removed focusonselect from peek

- src/styles/base/_variables.scss
- src/styles/typography/_base.scss
Adjusting typography line-height for small and x-small type styles, and letter-spacing for body and large.
Low - if for some reason some static heights (almost none) were decided based on the height calculated based on the line height of small or x-small text, they would be slightly off (by a couple pixels).  I don't believe that there are any cases like this, but there's no way to be certain.
https://masterclass-dev.atlassian.net/browse/DS-159
https://masterclass-dev.atlassian.net/browse/DS-160
> updating typography line-height and letter-spacing per designs request

- src/components/Modal/index.js
There was a problem discovered on production where videos within a modal could not enter into fullscreen mode.  This PR fixes that, while also still allowing modals to be opened within a fullscreen element.
go to a cm page
click header video to open modal
click the fullscreen button and ensure it enters fullscreen mode successfully
go to a class page
start last lesson in class
seek to end of video
ensure the NPS modal appears successfully
None - this fixes an existing issue
Not sure if a ticket or issue was filed yet
> Incident-128: Added fullscreen/descendent check to modal

- src/styles/components/_tile.scss
When mc tiles are inside a scrolling container they disappear on iOS devices.
It looks like `translateZ(0)` forces the browser to use hardware acceleration: https://stackoverflow.com/questions/8110580/ios5-images-disappear-when-scrolling-with-webkit-overflow-scrolling-touch
None
**Before (images disappearing):**
**After:**
Resolves #705 
No
> Fix iOS scrolling issues with mc-tile

- src/components/VideoPlayer/index.js
- src/styles/components/_video-player.scss
A big video play button is shown on the before screen passed down as `beforeScreen` prop into `VideoPlayer` component, this behavior is unexpected.
This PR hides the video play button when `beforeScreen` is used.
Low, just some style change.
Before:
After:
> Hide video play button on beforeScreen

- src/components/Carousel/index.js
- src/components/Carousel/index.stories.js
The loop property wasn't working correctly with our custom arrow component.  @jstnjns helped troubleshoot and address.
Low - removed the custom click handling for the arrow components and passed in the props that the slick dependency expects to make it behave as intended.
No visual change, but restores missing functionality to carousel component.
https://github.com/yankaindustries/mc-components/issues/647
> Fix looping

- src/components/VideoPlayer/index.js
- src/components/VideoPlayer/index.stories.js
- src/styles/components/_video-player.scss
For videos that autoplay in browsers that don't support autoplay with audio, we mute the video, add an additional control that calls out "tap to unmute" and then autoplay the video.
Low - if there are other overlays on videos there could be potential visual conflicts
#713 
> Adding "tap to unmute" for muted autoplay videos

- src/components/VideoPlayer/index.js
When unmounting the VideoPlayer component, check to see if the video instance exists before executing cleanup (otherwise an exception is thrown that kills the UI)
None
None
https://masterclass-dev.atlassian.net/browse/BLAM-81
> dont run cleanup if video instance doesnt exist

- src/components/Badge/index.js
- src/components/Badge/index.stories.js
- src/styles/components/_badge.scss
- src/styles/helpers/_theme-css-vars.scss
- src/utils/InvertedMirror.js
Design requested a new "bright" badge type.
None
Adds new type of badge called "bright":
https://masterclass-dev.atlassian.net/browse/DS-170
> Adding bright badge type

- .storybook/_upside-down.scss
- src/foundation/scale/index.stories.js
- src/styles/base/_functions.scss
- src/styles/base/mixins/_step.scss
- src/styles/components/_badge.scss
- src/styles/components/_modal.scss
- src/styles/components/_tooltip.scss
- src/styles/components/_video-player.scss
- src/styles/components/buttons/_buttons.scss
- src/styles/foundation/_foundation.scss
- src/styles/foundation/_scale.scss
- src/styles/index.scss
- src/styles/typography/_base.scss
Moving scale values to CSS variables. This allows us to reduce the LOC and complexity around using scale step values. The CSS output goes from 130kb -> 116kb (~5500 -> ~4500 LOC). Previously, we would use a SCSS mixin:
```scss
@import "~mc-components/dist/styles/scss/base/base";
.example {
@include step(padding: 6);
}
```
which would output:
```css
.example {
padding: 2rem;
}
@media (min-width: 768px) {
.example {
padding: 2.2rem;
}
}
@media (min-width: 960px) {
.example {
padding: 2.4rem;
}
}
```
Instead, we can now just use the CSS variable, and the our code is the same as the output
```scss
.example {
padding: var(--mc-scale-6)
}
```
Low - the existing mixin, which is used quite a bit, still works.  It just outputs the CSS variable now instead.
> Scale values to utilize CSS variables

- src/components/Button/index.stories.js
- src/styles/base/_variables.scss
- src/styles/components/buttons/_buttons.scss
Replacing the ApplePay button with Apple, as they should be unified and not so specific.  Apple's branding guidelines work for all of it's buttons.
Low - this deprecates `<Button kind='apple-pay'/>` and replaces it with <Button kind='apple' />.  Those instances need to get replaced.
Before
After
*BREAKING* - but not major
> <Button kind='apple' />

- src/styles/foundation/_scale.scss
- src/styles/typography/_base.scss
with the new CSS vars for scale sizes, had to override this odd font size (3.5 on the scale)
None - solves a bug where `.mc-text-small` is just the default body size
> fixing bug with .mc-text-small size

- src/components/VideoPlayer/index.js
<General description>
Right now, the video player's `onResume` function is not calling the "play" action when the prop `hasAutoplay` is false, causing the video player not correctly resuming the video playing.
Medium: This affects all video players on masterclass
> Local play should  be calling video.play and not pause

- .github/workflows/ci.yml
- ci.yml
See "Checks" tab, notice lint/build running in GitHub actions
Low - simply transferring checks from CCI to GH Actions.  Highest risk - checks failing because they are not set up correctly
> CI w/ GitHub Actions

- .storybook/_upside-down.scss
We had a bug on the storybook scale page after the refactoring of the scale to use css variables where it was rendering the demo with `rempx` values.
Fixed:
None - only affects storybook scss file.
Updates the "scale" story to show the correct px values for scale values.
https://github.com/yankaindustries/mc-components/issues/728
> Fix rempx bug on scale demo

- src/components/VideoPlayerScreen/index.js
After the end screen exits, the user wasn't able to interact with the video player clicking the screen for pausing or resuming.
Looks like a wrong state of the transition was adding a class to the end screen component when it should be hidden.
More info here: https://masterclass-dev.atlassian.net/browse/WE-202
Medium. Not sure why we had that function for defining when the transition ends, but maybe the code reviewers can clarify this.
No
> Fix end screen blocking clicks

- .storybook/_upside-down.scss
- .storybook/preview-head.html
- README.md
- src/styles/base/_variables.scss
Masterclass is going through a rebrand!  This is the first step - swapping Lato with Sohne.
Low - The font will still render as a default (Helvetica and Arial) if Sohne isn't available. 
N/A
**BREAKING** This change will require updates in the consumer apps.  The font is changing, so imports will need to be updated.
> Updating font to Sohne

- src/styles/typography/_base.scss
@jstnjns had the 700 font weight locally and noticed all the fonts on the review app looked too heavy.  After digging in, I realized I forgot to update the font weights in mc-components when swapping Lato with Sohne.  This PR updates the font weight for the headings to be the correct weight.
Low - just a weight change.
No visual changes to the majority of users (only users who had the `Sohne` font installed locally would see any difference...which is basically just @jstnjns).
N/A
> We only load 500 weights, not 700

- src/components/VideoPlayer/index.js
- src/styles/components/_video-player.scss
After getting feedback that the player wasn't working in some cases (international, first render, with text tracks, only in Safari), we hit up Brightcove and their resolution was to add `.vjs-tech` to the `<video>` tag.  So this is doing just that.
Medium - Unsure if there is any associated risk to applying a very generic class (that is seen elsewhere in the dynamically generated markup by Brightcove's player) to something that has not had it before.  Will mitigate with manual testing.
n/a
> VideoPlayer - odd bug fix

- src/utils/SourceLink.js
We've updated the default branch name a few times (from develop, to master, to main).  The helper to render the "view source" button on each component was never updated.  This updates that button so you can now link back to the source as expected.
None
N/A
N/A
> Changing base url based on develop to main name change

- src/styles/components/_background.scss
Fix for https://github.com/yankaindustries/mc-components/issues/766 - Issue with nesting `row` and `col` classes inside of the background component led to overflow issues because of inherited width values.
Low
https://github.com/yankaindustries/mc-components/issues/766
> Adding a width to the background container to deal with content overflow

- src/components/Checkbox/index.js
- src/components/CheckboxField/index.js
- src/components/CheckboxField/index.stories.js
CheckboxFields don't inherently display their errors like InputField and SelectFields do.  This means that any case where something like a CheckboxField is required and should be displaying an error has to be handled manually.  By wrapping it in a FormGroup with no label, we're able to get any wrapping context (error, warning, help, etc) that should come with the input.
Low - existing checkboxes with errors might display them now if they didn't before
> adding FormGroup to CheckboxField so that it may show an error state

- src/components/Dropdown/Dropdown.js
- src/styles/components/_dropdown.scss
Address some edge case resizing issues with the Dropdown component, and add a new `autoFlip` prop that has the ability to `disable` the autoflip functionality of the dropdown.
Low
Fixes this issue:
https://github.com/yankaindustries/mc-components/issues/524
> Fixing dropdown component resize issue, adding flip prop
