.storybook/styles.scss, src/styles/index.scss, src/styles/release-candidate/components/_c-button.scss
Instead of updating the component class names (high risk), update the existing class name styles instead (lower risk).
Low - Medium
Updates how the buttons look based on design-approved comps.  Only updates the primary, secondary, and tertiary button types.
N/A
=> Move mastersass button styles into c-button component

.stylelintrc, src/components/Footer/index.js, src/styles/release-candidate/components/_footer.scss
- Update from old markup and scss
- BEMify footer component
- Remove ids, move to classes
Low
Minor padding / shifting (removing reliance on old grid slowly)
N/A
=> Refactor footer component

src/components/Button/index.stories.js, src/components/CheckTile/index.stories.js, src/components/ImageTile/index.js, src/components/ImageTile/index.stories.js, src/styles/release-candidate/abstract/mixins/_ratios.scss, src/styles/release-candidate/components/_c-button.scss, src/styles/release-candidate/components/_overlay-check.scss, src/styles/release-candidate/components/_tile.scss
Align center the content inside the button.
Also, I fixed some errors introduced in https://github.com/yankaindustries/mc-components/pull/28
None
#32
=> Fix button content alignment

src/styles/components/_components.scss
Footer styles were removed in this PR https://github.com/yankaindustries/mc-components/pull/41
No
No
=> import Footer component styles

package.json, yarn.lock
Eslint rule fixes
* added ignoreTemplateLiterals to max-len
* removed jsx max props per line
* added more bool prop options
See https://github.com/yankaindustries/eslint-config-masterclass/commit/7da184b922d7c0c1890101a788183a8a597ac194
https://github.com/yankaindustries/mc-components/issues/44
=> version bump for eslint, fixing a few rules

.storybook/preview-head.html, src/components/VideoPlayer/index.js, src/components/VideoPlayer/index.stories.js, src/components/icons/ReplayIcon.js, src/styles/components/_components.scss, src/styles/components/_video-player.scss
Added a VideoPlayer component for brightcove video players. It's mostly a proof of concept until we try to use it in a feature. It may need some changes to make it more redux friendly, eg allowing props to be updated after creation and adding prop for pausing/playing the video.
None
No changes to existing components
=> VideoPlayer component

.storybook/addons.js, .storybook/config.js, package-lock.json, package.json, src/components/Badge/index.stories.js, src/components/Button/index.stories.js, src/components/Carousel/index.stories.js, src/components/CheckTile/index.stories.js, src/components/Footer/index.stories.js, src/components/GridExample/index.stories.js, src/components/HeaderLoggedIn/index.stories.js, src/components/ImageTile/index.stories.js, src/components/Input/index.stories.js, src/components/Modal/index.stories.js, src/components/RadioInput/index.stories.js, src/components/RoundedBox/index.stories.js, src/components/TextArea/index.stories.js, src/components/VideoPlayer/index.stories.js, yarn.lock
We wanted to visually separate out the static and react components in the storybook UI, this PR addresses the issue.
None / Low
- No visual changes to components
- Visual changes to storybook UI (added subsections for react components and static components)
Addresses: https://github.com/yankaindustries/mc-components/issues/16
=> Static markup

src/components/Carousel/index.stories.js
Change incorrect prop name for Carousel
None
=> Fix carousel story

__mocks__/fileMock.js, __mocks__/styleMock.js, package.json, src/components/Badge/__snapshots__/index.stories.storyshot, src/components/Button/__snapshots__/index.stories.storyshot, src/components/Carousel/__snapshots__/index.stories.storyshot, src/components/Carousel/index.js, src/components/Carousel/index.stories.js, src/components/CheckTile/__snapshots__/index.stories.storyshot, src/components/Footer/__snapshots__/index.stories.storyshot, src/components/GridExample/__snapshots__/index.stories.storyshot, src/components/GridExample/index.js, src/components/HeaderLoggedIn/__snapshots__/index.stories.storyshot, src/components/ImageTile/__snapshots__/index.stories.storyshot, src/components/Input/__snapshots__/index.stories.storyshot, src/components/Modal/__snapshots__/index.stories.storyshot, src/components/RadioInput/__snapshots__/index.stories.storyshot, src/components/RadioInput/index.stories.js, src/components/RoundedBox/__snapshots__/index.stories.storyshot, src/components/TextArea/__snapshots__/index.stories.storyshot, src/components/VideoPlayer/__snapshots__/index.stories.storyshot, src/components/VideoPlayer/index.stories.js, src/components/__tests__/storybooks.test.js, tools/testSetup.js, yarn.lock
Add snapshots for all the stories using Storyshots.
Noe
- Set up Jest
- Set up Enzyme
- Set up Storyshots
Resolves #4
=> Tests: Set up storyshots

src/styles/base/_variables.scss, src/styles/libraries/_libraries.scss, src/styles/libraries/bootstrap-overrides/_grid.scss
Design requested variable gutter widths depending on viewport size.  32px for desktop, 16px for mobile.
Could have conflicts with bootstrap grid, but looks ok with testing on react component.
Gutter sizes will change based on your viewport size
https://github.com/yankaindustries/mc-components/issues/55
=> Adding variable gutters

src/components/Badge/__snapshots__/index.stories.storyshot, src/components/Button/__snapshots__/index.stories.storyshot, src/components/Carousel/__snapshots__/index.stories.storyshot, src/components/CheckTile/__snapshots__/index.stories.storyshot, src/components/Footer/__snapshots__/index.stories.storyshot, src/components/GridExample/__snapshots__/index.stories.storyshot, src/components/HeaderLoggedIn/__snapshots__/index.stories.storyshot, src/components/HeaderLoggedIn/index.js, src/components/HeaderLoggedIn/index.stories.js, src/components/ImageTile/__snapshots__/index.stories.storyshot, src/components/Input/__snapshots__/index.stories.storyshot, src/components/Modal/__snapshots__/index.stories.storyshot, src/components/RadioInput/__snapshots__/index.stories.storyshot, src/components/RoundedBox/__snapshots__/index.stories.storyshot, src/components/TextArea/__snapshots__/index.stories.storyshot, src/components/VideoPlayer/__snapshots__/index.stories.storyshot
Added minimal option to the header when logged in. It displays only the logo on the navbar, and no other component to the left or the right.
None
=> Add minimal option for header

package.json
- Automatically runs test suite before allowing a version
- Commits only changes to `dist` folder on versioning
- Automatically increments version number and tags release on github
Might not work, since it has to be run from the develop branch to test
No visual change
N/A
=> Adding a script for versioning

src/components/ClassCard/__snapshots__/index.stories.storyshot, src/components/ClassCard/index.js, src/components/ClassCard/index.stories.js, src/styles/components/_class-card.scss, src/styles/components/_components.scss, src/utils/helpers.js
Add the Class Card component to mc-components
None
=> Add class card component

.gitignore, README.md, package.json
Update the documentation / readme around versioning instructions and update versioning scripts to handle github tagging for releases.
No
N/A
=> Preparation for better versioning

src/styles/components/_class-card.scss, src/styles/release-candidate/components/_badge.scss, src/styles/release-candidate/components/_header.scss, src/styles/release-candidate/components/_mobile-nav-button.scss, src/styles/release-candidate/components/_navbar-menu.scss
Missed changing a `$white` variable to `$mc-light` so the build was failing :(
No
N/A
=> Fix missing variable

README.md
Just testing our release process.
=> Updating readme with new release instructions

README.md
Updated readme / wiki links, but this is primarily a test to make sure our versioning system works for minor releases as well.
=> Version test for new minor version

src/components/HeaderLoggedIn/__snapshots__/index.stories.storyshot, src/components/HeaderLoggedIn/index.js
Don't display the mobile menu when the header is minimal
None
=> Bug: minimal logged in header displays the mobile hamburger menu

README.md, package.json
- Update test to minor version 0.2.0
- Update readme with wiki links
=> Deploy 0.2.0

src/components/Input/__snapshots__/index.stories.storyshot, src/components/Input/index.js, src/components/Input/index.stories.js, src/components/InputReduxForm/index.js, src/styles/base/_variables.scss, src/styles/components/forms/_input.scss
Add a warning prop to the input component.
None
=> Add warning to input component

package.json
Git wasn't pushed when versioning because I had the order wrong in the package scripts
No
N/A
N/A
=> Update versioning script order

src/styles/libraries/_libraries.scss
import scss style file instead of css
=> Import slick-carousel.scss

src/components/VideoPlayer/__snapshots__/index.stories.storyshot, src/components/VideoPlayer/index.js
Added prop to start a video on a specific time (last progress).
=> Added prop to start a video on specific time (last progress)

.storybook/styles.scss, src/components/Button/__snapshots__/index.stories.storyshot, src/components/Button/index.stories.js, src/utils/PropsTable.js
Adding a component to automatically generate a table of properties (like given in `withInfo`)
None
=> Adding PropsTable component

src/components/VideoPlayer/index.js
Added remainingTime to onTimeChanged callback function. We need this to be able to calculate the duration of the video.
=> Added RemainingTime to onTimeChange callback function

dist/components/VideoPlayer/index.js, package.json
=> Release v0.2.7

.storybook/styles.scss
=> Resolve conflicts in the file .storybook/styles.scss

src/components/Foundation/Type/index.stories.js, src/styles/base/_variables.scss, src/styles/typography/_typography.scss, src/styles/typography/base.scss, src/styles/typography/modifiers.scss
Updated based on the latest comps from design. Updated namespacing as well.
Medium - if any of these type styles are used right now they'll be affected.  I don't see them anywhere in the masterclass repo though.
Visual type changes and font size adjustments.
N/A
=> Updating type styles

src/styles/components/_class-card.scss, src/styles/components/_footer.scss, src/styles/components/_icons.scss, src/styles/components/_navbar-menu.scss, src/styles/components/_tile.scss, src/styles/components/_video-player.scss, src/styles/components/buttons/_button--types.scss, src/styles/release-candidate/components/_navbar-menu.scss, src/styles/typography/base.scss, src/styles/typography/modifiers.scss
Adds `mc-text--inverted` which can be added to any parent element or type element to invert the text color for use on a light background.  The default font color is "light", so using invert will change it to "dark".
None
Adds `mc-text--inverted` to change any text from white to black (including muted)
https://github.com/yankaindustries/mc-components/issues/149
=> Add "inverted" text modifier

src/components/Foundation/Type/index.stories.js
Storybook wasn't updated with the new text modifiers, so this PR adds them.
=> Showcase text modifiers in Storybook

src/components/ResponsiveHandler/index.js, src/components/ResponsiveHandler/index.stories.js, src/components/Tile/index.js, src/styles/base/_variables.scss, src/styles/components/_tile.scss
We need to be able to change prop values based on device width, this component allows you to do that. Similar to other handlers, ResponsiveHandler either executes children as a render function with arguments, or applies those same values as props to children.
Arguments/Props are:
- isXS
- isSM
- ltSM
- gteSM
- isMD
- ltMD
- gteMD
- isLG
- ltLG
- gteLG
- isXL
- ltXL
If we change breakpoint values in the CSS, they also need to get changed here.  Added a note in variables.scss to reflect that.
#148
=> Creating ResponsiveHandler

package.json
Since we removed testing, lets set preversion to lint instead as a minor sanity check
=> Add linting to preversion script

src/components/ButtonLoader/index.js
Make ButtonLoader to accept the color as prop so that we can change the color through react
None
#170
=> ButtonLoader color prop

src/foundation/grid/_styles.css, src/foundation/grid/index.stories.js, src/foundation/type/index.stories.js, src/styles/base/_variables.scss, src/styles/libraries/bootstrap-overrides/_grid.scss, src/utils/Placeholder.js
Updating grid system to have responsive gutter sizing, update documentation.
Low - doesn't seem like it's being used anywhere yet.
/Users/stephenpontes/Sites/mc-components/src/foundation/grid/index.stories.js
=> Responsive grid system gutters

.storybook/_upside-down.scss, src/foundation/variables/index.stories.js, src/styles/base/_variables.scss, src/styles/components/_badge.scss, src/styles/components/_carousel.scss, src/styles/components/_class-card.scss, src/styles/components/_footer.scss, src/styles/components/_header-logged-out.scss, src/styles/components/_header.scss, src/styles/components/_icons.scss, src/styles/components/_mobile-nav-button.scss, src/styles/components/_navbar-menu.scss, src/styles/components/_rounded-box.scss, src/styles/components/_tile.scss, src/styles/components/_video-player.scss, src/styles/components/buttons/_button--types.scss, src/styles/components/buttons/_button.scss, src/styles/components/forms/_input.scss, src/styles/components/forms/_radio-input.scss, src/styles/components/modal/_modal-content.scss, src/styles/components/modal/_modal-header.scss, src/styles/release-candidate/components/_badge.scss, src/styles/release-candidate/components/_header.scss, src/styles/release-candidate/components/_mobile-nav-button.scss, src/styles/release-candidate/components/_navbar-menu.scss, src/styles/typography/flourishes.scss, src/styles/typography/modifiers.scss
The Figma comp for mc-components is updated quite frequently:
Update the mc-components variables to reflect the latest mc-component changes to color variables.
I've also updated our documentation to show the variety of colors available to end users:
Low - mc-components has been built and checked for use of these variables. Any items that needed updates have been updated.  The main masterclass repo does not use these variables yet.
Visually changes the gray colors per design request.
N/A
=> Updating color variables to latest versions on figma comp

src/styles/components/_background.scss
Fix scss variable name error
None
=> Fix scss variable name error

.storybook/_upside-down.scss, src/foundation/variables/index.stories.js, src/styles/base/_variables.scss, src/styles/components/_carousel.scss, src/styles/components/_section.scss, src/styles/libraries/bootstrap-overrides/_grid.scss
Figma comp shows max width for containers lining up with breakpoint values, so updating code to reflect the understanding of grids.
Container widths changing may adjust / shift components on page
Minor
N/A
=> Changes to container max-widths

package.json, src/components/TileVideo/index.js, src/styles/animation/_animation.scss, src/styles/components/_tile.scss, src/styles/typography/base.scss
These are a handful of things that needed to be changed when implementing mc-components for the LIHP
LOW
Makes links not blue, fixes z-indexing issue for tiles
=> Minor fixes

src/components/VideoPlayer/index.js
Add `onSeek` event to the video player
None.
=> Add onseek event

src/components/Tile/index.stories.js, src/components/TileVideo/index.js, src/styles/components/_tile.scss
Videos in `TileVideo` will not show up until the video is ready to play, and then it fades in.
None - the only section currently using this is a branch for LIHP which is currently still open and mine (https://github.com/yankaindustries/masterclass/pull/7219).
=> `TileVideo` improvements

src/components/Button/index.stories.js, src/styles/components/buttons/_button.scss
Adding more clear disabled states and a storybook example on how to use it on buttons
None
Disabled button state
https://github.com/yankaindustries/mc-components/issues/248
=> Add story example for disabled buttons

src/components/Input/index.js
Input component: Fixes the no-label classname
None
=> Input: fix label class

src/foundation/type/beta.stories.js, src/styles/typography/_base.scss, src/styles/typography/_beta.scss, src/styles/typography/_modifiers.scss, src/styles/typography/_typography.scss
Test page for type styles
None
Adds new type styles page in storybook for quick prototyping and easy-to-see changes.
N/A
=> adding typography tests

.storybook/_upside-down.scss, src/foundation/type/beta.stories.js, src/styles/animation/_animation.scss, src/styles/components/_background.scss, src/styles/typography/_beta.scss
Updating beta typography responsive scaling with variable decay.
Also adds a grid example.
None, changes to zoom are reasonable
=> Improving step formula with decay, adding more beta typography examples

src/components/Carousel/index.js, src/components/Carousel/index.stories.js, src/styles/components/_carousel.scss
Was causing issues with overflow, and the use case isn't actually being used anywhere.  Quick solve.
None
=> Solving issue with scrollbar and fadeEdges

src/components/Background/index.js, src/components/Background/index.stories.js, src/components/Tile/index.stories.js, src/styles/components/_background.scss
The ability to add color to a Background component.  This will simplify how we apply common backgrounds to sections
None
=> Background color

src/components/index.js
We weren't exporting the background component for usage.
None - new component
Exports background component so it can be used
N.A
=> Need to export background for usage

src/components/VideoPlayer/index.js
https://masterclass-dev.atlassian.net/wiki/spaces/RET/pages/62750750/In-video+Keyboard+Controls
Breaking the video player in some unexpected way
The VideoPlayer component will now have keydown listeners to pause/play on spacebar, skip with side arrow keys, and increase/decrease volume with up/down arrow keys. These listeners should only be active while the video player is focused.
=> keyboard handlers on VidepPlayer component

src/styles/helpers/_helpers.scss, src/styles/helpers/_images.scss, src/styles/index.scss
Implement a responsive image handler
Low - not used anywhere
No visual changes, this is just a helper css class.
N/A
=> Adding responsive image helper

src/components/AnimationHandler/index.stories.js, src/components/Background/index.stories.js, src/components/ImageTile/index.js, src/components/ResponsiveHandler/index.stories.js, src/components/TileVideo/index.js, src/components/VideoPlayer/index.js, src/components/VideoPlayer/index.stories.js, src/utils/PropExample.js
Better documentation for the `<VideoPlayer />` component.  This includes prop definitions, function prop arguments, and demos.
None
#289
=> Improving documentation for <VideoPlayer />

src/styles/base/_variables.scss, src/styles/components/buttons/_button--inverted.scss, src/styles/components/buttons/_button--types.scss
Design requested changes to the tertiary button style
Low - design has cleared this for all existing use cases.
Old tertiary button:
New tertiary button:
New button is the same whether inverted or normal.
N/A
=> Tertiary button updates

src/components/Button/index.js, src/components/Button/index.stories.js, src/styles/components/buttons/_button.scss
Updating examples 
None
Make sure any button items are vertically centered (like icons) - Also update documentation to show the correct margins on button icons.
=> Updating button examples with icons

.storybook/styles.scss, src/components/FormGroup/index.js, src/components/InputField/index.js, src/components/SelectField/index.js, src/components/TextareaField/index.js, src/styles/components/forms/_checkbox.scss, src/styles/components/forms/_element.scss, src/styles/components/forms/_radio.scss, src/styles/components/forms/_select.scss
Feedback from design on minor form tweaks
None
=> Updating label margins, required->optional prop, and old libraries import

src/components/Tile/index.stories.js, src/components/TileProgress/index.stories.js, src/foundation/introduction/index.stories.js
Didn't have documentation around the scss file you'd need to import for basic variables or the TileProgress component.  This PR adds this.
None, just documentation changes
N/A
https://github.com/yankaindustries/mc-components/issues/373
=> Updating documentation for TileProgress and base scss file

.storybook/_upside-down.scss, src/components/Separator/index.js, src/components/Separator/index.stories.js, src/components/index.js, src/styles/components/_components.scss, src/styles/components/_separator.scss, src/utils/CodeExample.js
Simple component that renders a `<hr>` element to define a change in the content
None. It's a new component
=> Separator component

package.json, yarn.lock
Bootstrap changed the behavior of max-width on columns and we'd like to integrate this bugfix.
High - bootstrap is a core part of the grid system and bootstraps changes to their grid have the potential to affect large portions of our layouts.
https://github.com/yankaindustries/mc-components/issues/383
=> Updating bootstrap

src/components/AnimationHandler/index.stories.js
There was a bug with the animation handler example buttons. This fixes that.
None, documentation example
Correct visual bugs with missing transitions on animationhandler buttons.
NA
=> Fix bug on animation handler button examples

package.json
version scripts now support branches (beta)
Low
=> updating the version script to support branches and not publish

src/styles/typography/_base.scss
https://ourmasterclass.slack.com/archives/CB74RPL82/p1552690107044600
Approved by design, none
Adjusts default letter spacing on all body typography
N/A
=> Updating body letter spacing per design request

package.json, src/components/Input/index.js, src/components/Select/index.js, src/components/Textarea/index.js
Adds callback events as arguments to callback props (was previously missing)
None
=> Input callback events

src/styles/libraries/bootstrap-overrides/_grid.scss
Small gutters need a negative margin of a quarter of the gutter, was zero.
None
=> Fixing small gutters bug

src/components/Carousel/index.js, src/components/Carousel/index.stories.js
Adding documentation for:
- scrollCount
- showCount
- transition
None, documentation change only.
Storybook has three new documented props!
https://github.com/yankaindustries/mc-components/issues/434
=> Adding documentation for carousel properties

src/components/TileOverlay/index.stories.js
TileOverlay's properties were not fully documented. Let's fill in the gaps and document the different types as well as the color prop.
None, documentation change
Adds more examples in storybook
https://github.com/yankaindustries/mc-components/issues/433
=> Document different available tileOverlays

src/components/Carousel/index.js, src/components/Carousel/index.stories.js, src/components/Legacy/Carousel/index.js
Set new requirements for Carousel Arrow direction, but didn't update the implementation.  This fixes that.
None
=> fixing direction values for carousel

src/components/FormGroup/index.js, src/components/Forms/index.stories.js, src/components/InputField/index.js, src/components/InputField/index.stories.js, src/components/SelectField/index.js, src/components/SelectField/index.stories.js, src/components/TextareaField/index.js, src/components/TextareaField/index.stories.js
Removing margin from FormGroup
Low, layouts that expect the margin will need to be updated to supply it.
#407
=> Removing FormGroup margin

src/components/Background/index.js, src/components/Background/index.stories.js, src/styles/components/_background.scss
Adding a "dim" color to the Background component.
None
=> Background - color: dim

src/styles/base/_variables.scss
We've come across a lot of cases where our current light grays aren't sufficient.Adding one now between grey07 and white in anticipation of Sean's recipe cards
None
Adds a new shade of gray
N/A
=> Adding a new shade of gray

src/components/Dropdown/index.js, src/styles/components/_dropdown.scss
Combo of being able to use the same click outside of a dropdown to open a new dropdown (or any other click handler), as well as toggle the dropdown.
None - fixes bug
=> Fixing double toggle issue, better scroll styles for dropdown

src/components/Button/index.js, src/components/Tooltip/index.stories.js, src/components/TooltipContent/index.js
Apparently, like a fool, I changed the `Button` component to use an anchor instead of a button.  This messes up form submits because an anchor is not recognized as a proper submit element.
None - bug fix
=> Button - is actual button

src/components/Dropdown/index.js, src/styles/components/_dropdown.scss
I implemented Popper for dropdowns, but didn't test for mobile.
None - fixes a bug
=> Fixing dropdown styles on mobile

src/components/Button/index.js, src/styles/base/mixins/_ratios.scss
Adding the ability to have the Button choose a component or element to render (defaults to `button`).
Low - There shouldn't be any unintended circumstances that I'm aware of
=> Adding the ability for the Button to render another component/element

src/components/Button/index.js, src/components/Tooltip/index.js, src/components/Tooltip/index.stories.js, src/components/TooltipContent/index.js, src/components/TooltipContentControlled/index.js, src/components/TooltipToggle/index.js, src/components/helpers.js, src/styles/components/_tooltip.scss
Implementing the controlled aspect of a Tooltip.
Also improved documentation for Tooltip.
None - New component, minor changes to the inner workings of Tooltip as a whole
=> Tooltip - Controlled Component

src/components/Button/index.js, src/components/ClickOutside/index.js, src/components/Dropdown/index.js, src/components/Dropdown/index.stories.js, src/components/DropdownContent/index.js, src/components/DropdownContentControlled/index.js, src/components/DropdownItem/index.js, src/components/DropdownToggle/index.js, src/components/Tooltip/index.js, src/components/TooltipContentControlled/index.js, src/styles/components/_dropdown.scss
Adding controlled Dropdown functionality
None - new component and added functionality.  Nothing changing from existing implementations.
=> Dropdown - Controlled

build/assets.js
Don't try to compile hidden files in the icon folder into actual icons
Low
N/A
https://github.com/yankaindustries/mc-components/issues/466
=> Fix bug related to build process for hidden files in assets folder

src/components/Modal/index.js
Fix issue with the body class.
Resolves #529
=> Add modal class to the body when the modal mounts opened

src/styles/typography/_base.scss, src/styles/typography/_modifiers.scss
The letter spacing in figma and this repo were out of sync. This brings them back in sync.
None - design approved
Letter spacing minor adjustments
N/A
=> Updating letter spacing to match figma

src/components/Toast/index.js, src/components/Toast/index.stories.js, src/styles/base/_variables.scss, src/styles/components/_components.scss, src/styles/components/_toast.scss
<General description>
<What's the risk level of merging this in? | None / Low / Medium / High>
=> initial pass at toast render

build/assets.js
Somebody made an oopsie so we're gunna go ahead and pretend it never happened <3
None
Restores the build script
Wasn't able to push a patch
N/A
For reference:
https://github.com/yankaindustries/mc-components/pull/550
=> Re-adding assets

.circleci/config.yml
Update circle CI to attempt a build to make sure everything compiles correctly
N/A
Adds an extra step to the circle ci test - attempt an actual build.
Should prevent us from deleting things that prevent versioning :D
No
=> Circle CI Update - attempt build

src/foundation/grid/index.stories.js
Wanted to highlight some of the bootstrap helper classes we import so other devs can use them as well (related to display and flex helpers). Updating documentation :D
None
Updates documentation around bootstrap
https://github.com/yankaindustries/mc-components/issues/542
Nope
=> Add better documentation for the available bootstrap helpers

src/foundation/typography/sizes.stories.js, src/foundation/typography/summary.stories.js, src/styles/typography/_base.scss
Adding three larger font sizes, "display"
None
#549 549
=> Adding D1, D2, and D3 display font-sizes

src/components/Carousel/index.js, src/components/Carousel/index.stories.js, src/styles/components/carousel/_base.scss, src/styles/components/carousel/_modifiers.scss
Adding support for fading out the right side of a `Carousel` when `peek` is active on desktop.
Low
=> Carousel - Peek Gradient

.storybook/_upside-down.scss, src/components/ScrollHandler/index.js, src/components/ScrollHandler/index.stories.js
simple scroll handler to wrap conditional logic regarding whether the window is scrolled to a certain position
one
N/A
https://github.com/yankaindustries/mc-components/issues/207
N/A
=> new ScrollHandler component

src/styles/helpers/_opacity.scss
Design wanted muted updated to 60% from 50%, this implements that change!
None
Changes opacity from 50-60%
https://masterclass-dev.atlassian.net/browse/DS-149
=> Updating opacity to 0.6 for muted

src/components/Loader/index.js
Pass props to the Loader Component
None
=> Pass props to the Loader Component

src/components/Toast/index.js, src/components/VideoPlayer/index.js
replace componentWillReceiveProps with componentDidUpdate before we can upgrade React (has warnings)
None, unless I messed up the logic
=> replace componentWillReceiveProps with componentDidUpdate

src/components/VideoPlayer/index.js
The VideoPlayer component was missing a proper errorHandler method.  Added so as to be able to catch scenarios where invalid videoId is provided or internet connection cuts out.
None
Just adds appropriate error-handling to the VideoPlayer component
N/A
=> [WA-131] added proper error handling to VideoPlayer

.storybook/config.js, src/components/AnimationHandler/index.stories.js, src/components/FullscreenHandler/index.stories.js, src/components/HoverHandler/index.stories.js, src/components/ResponsiveHandler/index.stories.js, src/components/ScrollHandler/index.stories.js, src/components/ToggleHandler/index.stories.js
Organizing the navigation order to make more sense.  This was a request from design.
None
Nothing to component code, just documenation changes
https://masterclass-dev.atlassian.net/browse/DS-155
=> Reorder Navigation

src/foundation/introduction/index.stories.js
Display version in the docs to make sure that I'm reading the latest version of the docs
None
No
=> Display version in the docs

src/components/Carousel/index.js
Just adding role tags to the carousel arrows to help with testing
None
backwards compatible
=> [RET-1465] Add role tag to carousel arrows

src/components/Carousel/index.js
Lazy loads images not shown by carousel
Low - easy to test
=> add lazy load to Carousel

src/components/Carousel/index.js, src/styles/components/carousel/_modifiers.scss
Lazy loads images not shown by carousel. Adjusts peek to work with new lazy load option.
Low - easy to test
=> Adds lazy load to Carousel

.storybook/webpack.config.js, src/components/VideoPlayer/index.js, src/components/VideoPlayer/index.stories.js, src/components/VideoPlayer/props.stories.js
Adhere's to the original `hasAutoplay` prop functionality, even when you change videos.
`hasAutoplay` is off, the video does not autoplay.  you change the `videoId`, and the new video would automatically play
`hasAutoplay` is off the video does not autoplay.  you change the `videoId`, and the new video does not autoplay as well
Low - the autoplay on second video could be expected, but i do not believe change this would be considered breaking functionality
=> VideoPlayer - changing `videoId` obeys `hasAutoplay`

src/styles/components/carousel/_base.scss
After @jstnjns ' work on the slick dots, chatted with meritt and he had some design feedback.
None
Visually changes dots
N/A
=> Updating dots from meritts suggestions

.github/workflows/cd.yml
Fixing issue with deploy on merge to main.  See this effectively working on `pull_request` event here: https://github.com/yankaindustries/mc-components/runs/969216501?check_suite_focus=true
=> Automate deployment to Storybook

src/styles/components/_tile.scss
making the tile image positioned absolute so that any unexpected cases where Tile's have non Tile layers
low
fixes a bug
=> bugfix: tile image

package.json, src/components/Video/Settings.js, src/components/Video/Source.js, src/components/Video/Time.js, src/components/Video/Video.js, src/components/Video/index.js, src/components/Video/index.stories.js, src/components/Video/useVideo.js, src/components/index.js, src/styles/components/_video.scss, yarn.lock
Adding HLS to the Video component via hls.js
None - nobody using this component
https://masterclass-dev.atlassian.net/jira/software/projects/WA/boards/101?selectedIssue=WA-329
=> Video - HLS Support

.storybook/_upside-down.scss, src/components/Badge/index.js, src/components/Badge/index.stories.js, src/components/Tags/index.js, src/components/Tags/index.stories.js, src/styles/components/_badge.scss, src/styles/components/forms/_forms.scss, src/styles/components/forms/_tags.scss, src/styles/helpers/_spacing-margin.scss, src/styles/helpers/_theme-css-vars.scss
Adding new `<Tags />` component!
https://yankaindustries.github.io/mc-components/?path=/story/components-forms-tags--tags
It accepts two props: `collection` and `onChange`.  Collection is an array of strings to be rendered as badges, and `onChange` is a callback method for when something has occurred within `Tags` that passes back the modified collection.  An example:
```
const collection = ['a', 'b', 'c']
// User clicks "X" on 'b' Badge
onChange(['a', 'c'])
```
This is a controlled component, so you'll need to maintain state for it.  This is incredibly simple with `useState`
```
const Example = () => {
const [items, setItems] = useState([])
return (
<Tags collection={items} onChange={setItems} />
)
}
```
**NOTE:** A follow-up component will eventually be created to automate the …
=> Tags component

src/styles/components/buttons/_buttons.scss
<General description>
Updating border radius of button to 12px to follow new design system.
<What's the risk level of merging this in? | None / Low / Medium / High>
None, kept changes to button only.
https://github.com/yankaindustries/mc-components/issues/780
=> Update Button component to have border radius 12px
